### ISSUE TITLE
Failed to unbreak out a port

### ISSUE THREAD

**Issue by slutati1536** [Azure/sonic-buildimage#6486] opened 2021-01-18 14:28 UTC
**Description**

After a negative check of try to unsplit the port, correctly unspliting a port failed

**Steps to reproduce the issue:**

1.sudo config interface breakout Ethernet4 2x50G
2.sudo config interface breakout Ethernet8 2x50G
3.sudo config interface breakout Ethernet8 1x100G
4.sudo config interface breakout Ethernet6 1x100G - failing is expected 
5.sudo config interface breakout Ethernet4 1x100G - expected to succeed but result in error:  Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed - but is expected to succeed and the error should be "failed to unbreak out port".

port Ethernet4 - breakout into Ethernet4 and Ethernet6,
so in order to return the port to the old setting we should unbreak port Ethernet4 (as we did to Ethernet8)
not Ethernet6. but after trying to unbreak Ethernet6, unbreaking Ethernet4 failes.

**Describe the results you received:**

command : sudo config interface breakout Ethernet4 1x100G
output: 
...
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed

**Describe the results you expected:**

Command: sudo config interface breakout Ethernet4 1x100G, should succeed as the 
command "sudo config interface breakout Ethernet8 1x100G" did.  

Additional information you deem important (e.g. issue happens only occasionally):

**Output of `show version`:**
root@r-panther-13:/home/admin# show version

SONiC Software Version: SONiC.dpb_qa_image.0-23134a64
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 23134a6
Build date: Fri Jan 15 08:52:11 UTC 2021
Built by: vadymh@r-build-sonic03

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2020T04244
Uptime: 12:06:06 up 5:32, 1 user, load average: 4.01, 4.38, 4.88

Docker images:
REPOSITORY TAG IMAGE ID SIZE
docker-syncd-mlnx dpb_qa_image.0-23134a64 72cd4f0bad6c 540MB
docker-syncd-mlnx latest 72cd4f0bad6c 540MB
docker-sflow dpb_qa_image.0-23134a64 070e94ad45b1 465MB
docker-sflow latest 070e94ad45b1 465MB
docker-snmp dpb_qa_image.0-23134a64 4513d9bbede9 436MB
docker-snmp latest 4513d9bbede9 436MB
docker-dhcp-relay dpb_qa_image.0-23134a64 e9f74defdbed 402MB
docker-dhcp-relay latest e9f74defdbed 402MB
docker-teamd dpb_qa_image.0-23134a64 4432208a6469 463MB
docker-teamd latest 4432208a6469 463MB
docker-nat dpb_qa_image.0-23134a64 b0f25765961f 466MB
docker-nat latest b0f25765961f 466MB
docker-router-advertiser dpb_qa_image.0-23134a64 875949f0ef94 395MB
docker-router-advertiser latest 875949f0ef94 395MB
docker-platform-monitor dpb_qa_image.0-23134a64 77567d9ce67c 683MB
docker-platform-monitor latest 77567d9ce67c 683MB
docker-lldp dpb_qa_image.0-23134a64 9bba135a3864 435MB
docker-lldp latest 9bba135a3864 435MB
docker-database dpb_qa_image.0-23134a64 ae8be589a33c 394MB
docker-database latest ae8be589a33c 394MB
docker-sonic-mgmt-framework dpb_qa_image.0-23134a64 9f7fe89d1421 608MB
docker-sonic-mgmt-framework latest 9f7fe89d1421 608MB
docker-orchagent dpb_qa_image.0-23134a64 5928b24d51e3 481MB
docker-orchagent latest 5928b24d51e3 481MB
docker-macsec dpb_qa_image.0-23134a64 b255f6b0ccf1 466MB
docker-macsec latest b255f6b0ccf1 466MB
docker-sonic-telemetry dpb_qa_image.0-23134a64 4e502f1867fd 469MB
docker-sonic-telemetry latest 4e502f1867fd 469MB
docker-fpm-frr dpb_qa_image.0-23134a64 684115a1f6cc 480MB
docker-fpm-frr latest 684115a1f6cc 480MB

**Attach debug file `sudo generate_dump`:**
start reproducing on Jan 18 14:09:28.528602
[breakout_logs.txt](https://github.com/Azure/sonic-buildimage/files/5830736/breakout_logs.txt)

**Comment by slutati1536** [comment] 2021-01-18 14:32
@zhenggen-xu @praveen-li

**Comment by zhenggen-xu** [comment] 2021-01-19 20:20
I assuming the Ethernet6 is not part of the platform.json root port,  in such case, the "4.sudo config interface breakout Ethernet6 1x100G - failing is expected" should fail at CLI level, and not impacting any subsequent commands. 
@samaity

**Comment by anshuv-mfst** [comment] 2021-01-20 16:22
@zhenggen-xu @praveen-li - could you please assign the issue to you, thanks.

**Comment by zhenggen-xu** [comment] 2021-01-20 20:08
It does not allow me to assign to samaity.

**Comment by samaity** [comment] 2021-01-20 20:51
checking the issue.

**Comment by vadymhlushko-mlnx** [comment] 2021-02-03 17:52
The reproduce happening if you follow the next instructions:
Initial mode was `1x100G[50G,40G,25G,10G]`

1. `sudo config interface breakout Ethernet4 2x50G`
2. `sudo config interface breakout Ethernet4 1x100G`

**Comment by zhenggen-xu** [comment] 2021-02-24 17:40
See: https://github.com/Azure/sonic-utilities/pull/1440

**Comment by zhenggen-xu** [comment] 2021-03-03 04:18
close it since code is merged.  Re-open if you see any more issue.

**Closed by zhenggen-xu** 2021-03-03 04:18 UTC
Labels: Port Breakout :trident:, Triaged
