### ISSUE TITLE
ERR syslog about pmon "ERR pmon#thermalctld[39]: Caught exception while initializing thermal manage"

### ISSUE THREAD

**Issue by tim-rj** [Azure/sonic-buildimage#5458] opened 2020-09-24 09:39 UTC
**Description**

ERR syslog about pmon "ERR pmon#thermalctld[39]: Caught exception while initializing thermal manage"

**Steps to reproduce the issue:**
1. reboot and cat syslog 

**Describe the results you received:**
ERR syslog about pmon "ERR pmon#thermalctld[39]: Caught exception while initializing thermal manage"

```
Sep 24 16:50:27.004547 sonic ERR pmon#thermalctld[39]: Caught exception while initializing thermal manager - 
Sep 24 16:50:27.086836 sonic ERR pmon#xcvrd[35]: :- initializeGlobalConfig: Sonic database config global file doesn't exist at /var/run/redis/sonic-db/database_global.json
Sep 24 16:50:27.780699 sonic ERR pmon#xcvrd[35]: :- initializeGlobalConfig: SonicDBConfig Global config is already initialized
```

**Describe the results you expected:**
no print err syslog

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

    ```
root@sonic:/home/admin# show version 

SONiC Software Version: SONiC.HEAD.182-75068f3a
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: 75068f3a
Build date: Tue Sep 15 20:56:19 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-ruijie_b6510-48vs8cq-r0
HwSKU: B6510-48VS8CQ
ASIC: broadcom
Serial Number: G1W10072
Uptime: 15:32:00 up 8 min,  1 user,  load average: 0.56, 2.74, 1.68

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-syncd-brcm             HEAD.182-75068f3a   e0a8a1e70567        436MB
docker-syncd-brcm             latest              e0a8a1e70567        436MB
docker-platform-monitor       HEAD.182-75068f3a   7a0b4c32e32a        357MB
docker-platform-monitor       latest              7a0b4c32e32a        357MB
docker-router-advertiser      HEAD.182-75068f3a   5b68a457b247        289MB
docker-router-advertiser      latest              5b68a457b247        289MB
docker-fpm-frr                HEAD.182-75068f3a   d68563ab47ff        334MB
docker-fpm-frr                latest              d68563ab47ff        334MB
docker-sflow                  HEAD.182-75068f3a   efaf9fdec8fb        314MB
docker-sflow                  latest              efaf9fdec8fb        314MB
docker-lldp-sv2               HEAD.182-75068f3a   eb734d856002        311MB
docker-lldp-sv2               latest              eb734d856002        311MB
docker-orchagent              HEAD.182-75068f3a   31ab84cddd9b        333MB
docker-orchagent              latest              31ab84cddd9b        333MB
docker-dhcp-relay             HEAD.182-75068f3a   0416f768a8aa        299MB
docker-dhcp-relay             latest              0416f768a8aa        299MB
docker-database               HEAD.182-75068f3a   6be94df5546f        289MB
docker-database               latest              6be94df5546f        289MB
docker-snmp-sv2               HEAD.182-75068f3a   7f94958e28db        347MB
docker-snmp-sv2               latest              7f94958e28db        347MB
docker-teamd                  HEAD.182-75068f3a   d1db1b60ffec        314MB
docker-teamd                  latest              d1db1b60ffec        314MB
docker-nat                    HEAD.182-75068f3a   a08bed4749c5        316MB
docker-nat                    latest              a08bed4749c5        316MB
docker-sonic-mgmt-framework   HEAD.182-75068f3a   4f9ba411a805        430MB
docker-sonic-mgmt-framework   latest              4f9ba411a805        430MB
docker-sonic-telemetry        HEAD.182-75068f3a   ad6b2e2569f2        353MB
docker-sonic-telemetry        latest              ad6b2e2569f2        353MB
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by jleveque** [comment] 2020-10-03 17:51
Removed the "Issues for 201911" label, as this platform is not supported in 201911; in fact support for this platform is not yet even included in the master branch (it is currently in pull request [here](https://github.com/Azure/sonic-buildimage/pull/4954)).

**Comment by jleveque** [comment] 2020-10-03 17:51
@Junchao-Mellanox: Can you please investigate this thermalctld exception and why there is no error message appended to the message? Support for the platform in question is currently under pull request [here](https://github.com/Azure/sonic-buildimage/pull/4954).

**Comment by Junchao-Mellanox** [comment] 2020-10-09 09:42
> @Junchao-Mellanox: Can you please investigate this thermalctld exception and why there is no error message appended to the message? Support for the platform in question is currently under pull request [here](https://github.com/Azure/sonic-buildimage/pull/4954).
> 
> Also, it appears this message is also seen on other platforms.

Will create a PR to fix this. The issue is at line:
```python
self.log_error('Caught exception while initializing thermal manager - {}'.format(e))
```
Need change it to:
```python
self.log_error('Caught exception while initializing thermal manager - {}'.format(repr(e)))
```
And i need also catch the NotImplementedError and log a warning message.

**Comment by jleveque** [comment] 2021-01-07 22:25
Fixed via https://github.com/Azure/sonic-platform-daemons/pull/103 (submodule updated in https://github.com/Azure/sonic-buildimage/pull/5741).

**Closed by jleveque** 2021-01-07 22:25 UTC
