### ISSUE TITLE
[DPB] BGP_NEIGHBOR yang model causing DPB errors

### ISSUE THREAD

**Issue by alexrallen** [Azure/sonic-buildimage#7959] opened 2021-06-23 21:52 UTC
https://github.com/Azure/sonic-buildimage/pull/6917 introduced a model for BGP_NEIGHBOR in Yang. However:

1. It does not support defining a neighbor without an explicit VRF
2. It does not support any fields inside a BGP_NEIGHBOR entry in CONFIG_DB such as asn or holdtime. 

## Defining Neighbor without VRF

This model expects the neighbors to be defined as 
```
   "BGP_NEIGHBOR": {
        "default|10.0.0.1": {}
   }
```

where default is the VRF name and does not support defining the neighbor without this. This is because the Yang model defines the vrf name as part of the key for BGP neighbor entries. 

### Steps to Reproduce

1. Install latest master on switch
2. Disable ZTP via `ztp disable -y`
3. Update the config if neccesary via `/usr/local/bin/sonic-cfggen -H -k [SKU] --write-to-db`
4. Edit config_db to include the following minimal BGP Neighbor config

```
   "BGP_NEIGHBOR": {
        "10.0.0.1": {}
   }
```

5. Run `config reload -y`
6. Attempt to break out any port

### Observed Results
Breakout fails with the following error....

```
sonic_yang(3):All Keys are not parsed in BGP_NEIGHBOR
dict_keys(['10.0.0.1'])
sonic_yang(3):exceptionList:[]
```

### Expected Results

Successful Breakout

## Does not support fields in neighbor entry

This model also does not support any fields being in the neighbor entry. For example..

```
   "BGP_NEIGHBOR": {
        "default|10.0.0.1": {
            "asn": "65000"
        }
   }
```

This will throw an error that the asn key is not matched. This functionality is implemented in this Yang model through the `uses` and `grouping` keywords. These do not appear to be functioning in the expected manner because if I copy the leafs manually into the container definitions then it correctly matches the fields. 

### Steps to Reproduce

1. Configure your config_db.json to have the following BGP_NEIGHBORS config

```
"BGP_GLOBALS": {
    "default": {}
},
"BGP_NEIGHBOR": {
    "default|10.0.0.1": {
        "asn": "65000"
    }
}
```

2. Run `config reload -y`
3. Attempt to break out any port

### Observed Results 

The breakout fails with the following error....

```
sonic_yang(3):All Keys are not parsed in BGP_NEIGHBOR
dict_keys(['default|10.0.0.1'])
sonic_yang(3):exceptionList:['"asn"']
```

### Expected Results

Successful breakout

**Comment by praveen-li** [comment] 2021-06-24 01:19
>>>This will throw an error that the asn key is not matched. This functionality is implemented in this Yang model through the uses and grouping keywords. These do not appear to be functioning in the expected manner because if I copy the leafs manually into the container definitions then it correctly matches the fields.

@robocoder99 
-- Kindly paste relevant yang models field. 

@venkatmahalingam
-- We need to check if grouping is supported  in Python yang library or not. 
-- We need to add missing fields if these are allowable configs.

**Comment by venkatmahalingam** [comment] 2021-06-25 05:21
@robocoder99 
It does not support any fields inside a BGP_NEIGHBOR entry in CONFIG_DB such as asn or holdtime.
-> We have these fields in the BGP_NEIGHBOR table, did you get any error for these fields? since the key is different (expect VRF anem as well) now in YANG, how did you get to check the fields?

**Comment by robocoder99** [comment] 2021-06-25 17:00
@venkatmahalingam  Please see my "steps to reproduce section" this includes all details to produce a minimal recreation of the bug.

**Comment by venkatmahalingam** [comment] 2021-06-28 04:47
Created the PR https://github.com/Azure/sonic-buildimage/pull/7992/files to fix this issue.

**Comment by dgsudharsan** [comment] 2021-08-30 05:36
@alexrallen  Can you please close this as the fix is merged?

**Closed** 2021-09-16 20:14 UTC
Labels: Bug :bug:, Port Breakout :trident:, yang
