### ISSUE TITLE
DaemonBase: object has no attribute 'syslog'

### ISSUE THREAD

**Issue by jleveque** [Azure/sonic-buildimage#4034] opened 2020-01-17 01:04 UTC
In the `signal_handler()` method, the DaemonBase class references member object "syslog", but it doesn't exist (see https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-daemon-base/sonic_daemon_base/daemon_base.py; lines 105, 107, 110, 113). Unsure if DaemonBase was intended to be derived from the Logger class, or if it was meant to instantiate a Logger member object and reference that instead.

```
pmon#supervisord: ledd Traceback (most recent call last):
pmon#supervisord: ledd   File "/usr/bin/ledd", line 118, in <module>
pmon#supervisord: ledd     main()
pmon#supervisord: ledd   File "/usr/bin/ledd", line 115, in main
pmon#supervisord: ledd     ledd.run()
pmon#supervisord: ledd   File "/usr/bin/ledd", line 90, in run
pmon#supervisord: ledd     (state, c) = sel.select(SELECT_TIMEOUT)
pmon#supervisord: ledd   File "/usr/lib/python2.7/dist-packages/swsscommon/swsscommon.py", line 808, in select
pmon#supervisord: ledd     return _swsscommon.Select_select(self, timeout)
pmon#supervisord: ledd   File "/usr/local/lib/python2.7/dist-packages/sonic_daemon_base/daemon_base.py", line 110, in signal_handler
pmon#supervisord: ledd     self.syslog.syslog(self.syslog.LOG_INFO, "Caught SIGTERM - exiting...")
pmon#supervisord: ledd AttributeError: 'DaemonLedd' object has no attribute 'syslog'
```

**Comment by jleveque** [comment] 2020-01-17 01:05
@stephenxs: Can you please look into this? It appears as though it was introduced by your PR https://github.com/Azure/sonic-buildimage/pull/3281

**Comment by stephenxs** [comment] 2020-01-17 01:08
@jleveque sure, will check it.

**Comment by msosyak** [comment] 2020-01-17 10:12
I guess that `self.` before syslog is redundant as syslog is a module imported, not a member of some class.

**Comment by stephenxs** [comment] 2020-01-17 15:43
Hi @jleveque,
Originally syslog was a module imported in daemon_base.py, introducing an issue which was fixed in [PR 3281](https://github.com/Azure/sonic-buildimage/pull/3281). The PR was intended to introduce a logic to enforce class Logger is destroyed ahead of module syslog being destroyed by define module syslog as a member of class Logger. It has nothing to do with the DaemonBase class.
So I think @msosyak is right. The `self.` before syslog is redundant because syslog isn't a member of DaemonBase class.

**Comment by stephenxs** [comment] 2020-01-17 16:19
Hi @jleveque , I create a draft PR to resolve this issue. can you take a look? [# 4039](https://github.com/Azure/sonic-buildimage/pull/4039)

**Closed** 2020-02-12 14:57 UTC
Labels: Bug :bug:
