### ISSUE TITLE
DHCP relay forwards incorrect DHCP client packet to DHCP server(in case of DHCP packet without payload)

### ISSUE THREAD

**Issue by ppikh** [Azure/sonic-buildimage#6052] opened 2020-11-26 12:34 UTC
[dump_on_dhcp_server_side.pcap.gz](https://github.com/Azure/sonic-buildimage/files/5603026/dump_on_dhcp_server_side.pcap.gz)
[dump_on_dut_dhcp_client_vlan.pcap.gz](https://github.com/Azure/sonic-buildimage/files/5603029/dump_on_dut_dhcp_client_vlan.pcap.gz)

**DHCP relay forwards incorrect DHCP client packet to DHCP server(in case of DHCP packet without payload)**

DHCP relay forwards incorrect DHCP client packet to DHCP server(in case of DHCP packet without payload)
Issue happens in case when send DHCP packet via scapy without DHCP payload.
Packet example:  Ether(src="0c:42:a1:17:e6:fd",dst="ff:ff:ff:ff:ff:ff")/IP(src="0.0.0.0",dst="255.255.255.255")/UDP(sport=68,dport=67)/BOOTP(chaddr='0c42a117e6fd'.decode('hex'),xid=RandInt())/DHCP()

**Setup**:
SONiC device has 2 connected Linux hosts(host A, host B)
Host A connected from port enp4s0f1 to SONiC port Ethernet124
Host B connected from port enp6s0f1 to SONiC port Ethernet60
Host A acts as DCHP client, 
Host B acts as DCHP server and has next network configuration:
sudo ip addr add 69.0.0.2/24 dev enp6s0f1
sudo ip route add 69.0.1.0/24 via 69.0.0.1

**Steps to reproduce the issue:**
1. Configure DUT:
sudo config interface ip add Ethernet60 69.0.0.1/24
sudo config vlan add 690
sudo config vlan member add --untagged 690 Ethernet124
sudo config interface ip add Vlan690 69.0.1.1/24
sudo config vlan dhcp_relay add 690 69.0.0.2
2. Send from DHCP client empty DHCP packet using scapy:
pkt = Ether(src="0c:42:a1:17:e6:fd",dst="ff:ff:ff:ff:ff:ff")/IP(src="0.0.0.0",dst="255.255.255.255")/UDP(sport=68,dport=67)/BOOTP(chaddr='0c42a117e6fd'.decode('hex'),xid=RandInt())/DHCP()
sendp(pkt, iface='enp4s0f1')
3. Check packet to DHCP server side

**Describe the results you received:**
DHCP packet arrived to DHCP server, but it modified and have some unexpected data. For example in packet added option 12 - with some hostname, also added option 50 - with requested IP - which is not in DHCP server subnet and other.
See attached PCAP files(use: "tar -xf file_name.pcap..gz"  for unpack).

**Describe the results you expected:**
DHCP packet forwarded to DHCP server without modification, only DHCP relay option 82 should be added.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue reproduce only in case of DHCP packet without payload.

 ```
SONiC Software Version: SONiC.201911.30-dirty-20201124.120644
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: ac5117f2
Build date: Tue Nov 24 11:57:24 UTC 2020
Built by: sw-r2d2-bot@r-build-sonic-ci02

Platform: x86_64-mlnx_msn3700-r0
HwSKU: ACS-MSN3700
ASIC: mellanox
Serial Number: MT1949X06182
Uptime: 12:27:39 up 13:35,  1 user,  load average: 1.88, 1.52, 1.14

Docker images:
REPOSITORY                    TAG                               IMAGE ID            SIZE
docker-syncd-mlnx             201911.30-dirty-20201124.120644   e758fd3a3240        399MB
docker-syncd-mlnx             latest                            e758fd3a3240        399MB
docker-sonic-telemetry        201911.30-dirty-20201124.120644   4354e24f368d        353MB
docker-sonic-telemetry        latest                            4354e24f368d        353MB
docker-router-advertiser      201911.30-dirty-20201124.120644   74d4310804b7        290MB
docker-router-advertiser      latest                            74d4310804b7        290MB
docker-platform-monitor       201911.30-dirty-20201124.120644   2904669937a5        665MB
docker-platform-monitor       latest                            2904669937a5        665MB
docker-fpm-frr                201911.30-dirty-20201124.120644   804893596a66        335MB
docker-fpm-frr                latest                            804893596a66        335MB
docker-teamd                  201911.30-dirty-20201124.120644   43862681ed22        315MB
docker-teamd                  latest                            43862681ed22        315MB
docker-lldp-sv2               201911.30-dirty-20201124.120644   96bf1ad6f224        312MB
docker-lldp-sv2               latest                            96bf1ad6f224        312MB
docker-dhcp-relay             201911.30-dirty-20201124.120644   90aa45d7faf6        300MB
docker-dhcp-relay             latest                            90aa45d7faf6        300MB
docker-database               201911.30-dirty-20201124.120644   eaac4565aec3        289MB
docker-database               latest                            eaac4565aec3        289MB
docker-snmp-sv2               201911.30-dirty-20201124.120644   4046aec714f3        348MB
docker-snmp-sv2               latest                            4046aec714f3        348MB
docker-orchagent              201911.30-dirty-20201124.120644   7bb60251023b        333MB
docker-orchagent              latest                            7bb60251023b        333MB
docker-sflow                  201911.30-dirty-20201124.120644   40dcd66b4af4        315MB
docker-sflow                  latest                            40dcd66b4af4        315MB
docker-nat                    201911.30-dirty-20201124.120644   40757ed6bbfb        316MB
docker-nat                    latest                            40757ed6bbfb        316MB
docker-sonic-mgmt-framework   201911.30-dirty-20201124.120644   354cc3e4d510        427MB
docker-sonic-mgmt-framework   latest                            354cc3e4d510        427MB
 ```

**Comment by tahmed-dev** [comment] 2020-11-26 15:06
@ppikh Thanks for reporting. This is an interesting scenario. Can you please instead of capturing from client/servers ends, do packet capture from the relay vlan port it is listening to and from uplink ports it sends packet through?

**Comment by ppikh** [comment] 2020-11-26 15:44
@tahmed-dev file **dump_on_dut_dhcp_client_vlan.pcap.gz** created on DUT(SONiC) side on VLAN interface 690.
I used: tcpdump -i Vlan690 -w file.pcap

File **dump_on_dhcp_server_side.pcap.gz** created on DHCP server side

Do you still need packet on interface to which connected DHCP server from DUT side, like run: "tcpdump -i Ethernet60 -w file.pcap"?

**Comment by tahmed-dev** [comment] 2020-11-26 16:43
@ppikh Yes, please. I want to make sure that any option addition is indeed coming from the relay. The options are client based options and the relay doesn't how to fill them in. So, it is either sending garbage data, or it was indeed received that way. To rule out the latter, it is good to see what is being received on the downlink of the vlan interface. Also, capture on the uplink interface + default route interface will show outgoing packet from the relay.

**Comment by ppikh** [comment] 2020-11-27 16:21
@tahmed-dev Please see bellow 3 dumps from different interfaces on DUT.
Dump on VLAN interface to which connected DHCP client
[dump_vlan690_iface.pcap.gz](https://github.com/Azure/sonic-buildimage/files/5608795/dump_vlan690_iface.pcap.gz)

Dump on SONiC MGMT interface(default route)
[dump_on_default_route_mgmt_iface.pcap.gz](https://github.com/Azure/sonic-buildimage/files/5608796/dump_on_default_route_mgmt_iface.pcap.gz)

Dump on interface to which connected DHCP server
[dump_iface_connected_to_dhcp_server.pcap.gz](https://github.com/Azure/sonic-buildimage/files/5608797/dump_iface_connected_to_dhcp_server.pcap.gz)

**Comment by tahmed-dev** [comment] 2020-11-29 05:05
@ppikh, can you please try your test with this [image](https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/6315/artifact/target/sonic-mellanox.bin)?

**Comment by ppikh** [comment] 2020-12-02 15:44
@tahmed-dev Sorry, but looks like image not available. I had no time to check it before. Can you please build new image?

**Comment by tahmed-dev** [comment] 2020-12-02 19:32
@ppikh, no worries. I triggered another. Build artifacts are [here](https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/6351/artifact/target/)

**Comment by ppikh** [comment] 2020-12-03 15:47
@tahmed-dev Hi, I still do not see this artifact. In Jenkins history I see jobs since 1 Dec. But your build 6351 is not here. How it is possible? Oldest Jenkins build 6366 has build date 1 Dec 2020. Please check link for artifacts. Thanks

**Comment by tahmed-dev** [comment] 2020-12-03 17:42
@ppikh my mistake, it was a stale link. Here is the [link](https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all-pr/6389/artifact/target/). Also, if the build artefact gets deleted, feel free to trigger a build in [PR:6057](https://github.com/Azure/sonic-buildimage/pull/6057)

**Comment by ppikh** [comment] 2020-12-09 17:03
@tahmed-dev 
Hi, I checked on your image SONiC.HEAD.6389-33344befc - issue does not reproduce.

**Comment by tahmed-dev** [comment] 2020-12-12 00:26
> @tahmed-dev
> Hi, I checked on your image SONiC.HEAD.6389-33344befc - issue does not reproduce.

Thanks @ppikh for the great help. Will close this issue via [PR:6057](https://github.com/Azure/sonic-buildimage/pull/6057)

**Closed** 2020-12-12 00:28 UTC
Labels: Triaged

**Comment by osydoren** [comment] 2020-12-24 08:10
@ppikh
Hi. I started working with this issue and I tried to reproduce it on my setup. I have Mellanox Spectrum SN2700 switch and I used the build from master branch. But I am having problems. I applied the configuration you described in the issue, the configuration is being applied successfully. Next, on the client DUT using Scapy, I generated DHCP discovery packet and sent it in the direction of the switch, destination mac address is broadcast, the source IP is set to all zero, the destination IP is set to all 255 since we send this packet in the direction of the Relay Agent and the Relay Agent should modify this packet into unicast and send it to the DHCP server. But in my case, all the packets that came to the switch are dropped in Vlan690. I see that packets enter the physical port, the corresponding counter in the statistics is incremented, also I see that RX_ERR counter from the rifcounters for Vlan690 being incremented, so all the packets are dropped in my case and I was not been able to find exact reason why packets are dropped. I sorted out around this and I can say that I see 3 possible reasons why my packages are dropped, 1) broadcast mac address - perhaps the flooding control is enabled by default and did not find cli commands to check it, 2) 0.0.0.0 source IP - it seems to me that this is invalid value and I saw a test in Sonic repository for this, the test specifically checks that packets that contain such a value in the IP header should be dropped, 3) 255.255.255.255 destination IP - I think the same as in 2 but may be wrong. If I change all these fields to make packet unicast with valid IPs it stops dropping it.

Based on this, I want to ask you, did you attach the full configuration to the issue, or is there something else that needs to be configured so that these packets are not dropped by the switch, perhaps something needs to be configured additionally.
Since I do not have much experience in relay agent and how it works in sonic, I want to ask you what needs to be configured additionally, or perhaps you have any assumptions based on the information I provided that something is not working correctly on my config or is invalid or maybe I am doing something wrong or I should look at something else.
Any help from you would be greatly appreciated.
Thanks

**Comment by d-dashkov** [comment] 2021-02-12 10:27
Hello,
I have stumbled upon this issue while trying to setup DHCP relay on Mellanox SN2700.
Packages do not reach the DHCP server from the client.
```
                    +--------------------------------------+
+---------------+   |                                      |   +---------------+
|               |   | +------------+  relay +------------+ |   |               |
|               |   | |            +<-------+            | |   |               |
|  DHCP Server  +-----+   Vlan30   |        |   Vlan20   +-----+    Client     |
|  30.0.0.202   |   | |  30.0.0.1  |        |  20.0.0.1  | |   |   20.0.0.201  |
|               |   | +------------+        +------------+ |   |               |
+---------------+   |                                      |   +---------------+
                    +--------------------------------------+

+-----------+--------------+------------+----------------+-----------------------+-------------+
|   VLAN ID | IP Address   | Ports      | Port Tagging   | DHCP Helper Address   | Proxy ARP   |
+===========+==============+============+================+=======================+=============+
|        20 | 20.0.0.1/24  | Ethernet64 | untagged       | 30.0.0.202            | disabled    |
+-----------+--------------+------------+----------------+-----------------------+-------------+
|        30 | 30.0.0.1/24  | Ethernet72 | untagged       |                       | disabled    |
+-----------+--------------+------------+----------------+-----------------------+-------------+
```
I researched that DHCP discovery packets are dropping on the interface and not even getting into Vlan 20($ tcpdump -i Vlan20 port 67 or port 68 -e -n -vv).
Also, if I tried to generate a DHCP packet on Vlan20($ dhclient -v Vlan20), it did not come to Vlan30.

```
admin@sonic:~$ show ve

SONiC Software Version: SONiC.master.514-f99dbff7
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: f99dbff7
Build date: Thu Jan  7 11:32:16 UTC 2021
Built by: johnar@jenkins-worker-7

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2020T04280
Uptime: 12:23:17 up 11 days,  1:49,  1 user,  load average: 8.95, 6.59, 5.69

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-syncd-mlnx             latest                8537800d1c46        536MB
docker-syncd-mlnx             master.514-f99dbff7   8537800d1c46        536MB
docker-sflow                  latest                0a822def5cfe        452MB
docker-sflow                  master.514-f99dbff7   0a822def5cfe        452MB
docker-snmp                   latest                2069a95759c9        432MB
docker-snmp                   master.514-f99dbff7   2069a95759c9        432MB
docker-teamd                  latest                08b104d44f5b        451MB
docker-teamd                  master.514-f99dbff7   08b104d44f5b        451MB
docker-router-advertiser      latest                8cb6defab300        391MB
docker-router-advertiser      master.514-f99dbff7   8cb6defab300        391MB
docker-platform-monitor       latest                5276a7643b58        672MB
docker-platform-monitor       master.514-f99dbff7   5276a7643b58        672MB
docker-lldp                   latest                b246a382937e        431MB
docker-lldp                   master.514-f99dbff7   b246a382937e        431MB
docker-database               latest                01e9cf4ea8cf        391MB
docker-database               master.514-f99dbff7   01e9cf4ea8cf        391MB
docker-orchagent              latest                b0ef7ae5f9a4        468MB
docker-orchagent              master.514-f99dbff7   b0ef7ae5f9a4        468MB
docker-nat                    latest                33f3d25505eb        453MB
docker-nat                    master.514-f99dbff7   33f3d25505eb        453MB
docker-sonic-telemetry        latest                873eda70c348        465MB
docker-sonic-telemetry        master.514-f99dbff7   873eda70c348        465MB
docker-dhcp-relay             latest                90a1733f4c5d        397MB
docker-dhcp-relay             master.514-f99dbff7   90a1733f4c5d        397MB
docker-sonic-mgmt-framework   latest                c6b96579ad33        604MB
docker-sonic-mgmt-framework   master.514-f99dbff7   c6b96579ad33        604MB
docker-fpm-frr                latest                d71593b61940        468MB
docker-fpm-frr                master.514-f99dbff7   d71593b61940        468MB

```
[config_db.txt](https://github.com/Azure/sonic-buildimage/files/5971065/config_db.txt)

Could you help to solve this out?
Thanks!
