### ISSUE TITLE
[Broadcom platform] CLI change MTU causes portmgrd crashed

### ISSUE THREAD

**Issue by vincentchiang-ec** [Azure/sonic-buildimage#8404] opened 2021-08-10 01:13 UTC
#### Description

Use CLI to change MTU, portmgrd is crashed.

#### Steps to reproduce the issue:
1. Use CLI "sudo config interface mtu Ethernet0 1501" to change MTU value

#### Describe the results you received:
Syslog:
```
Aug 10 00:51:19.879027 sonic NOTICE swss#orchagent: :- doPortTask: Set port Ethernet0 MTU to 1501
Aug 10 00:51:19.880180 sonic NOTICE swss#orchagent: :- setRouterIntfsMtu: Set router interface Ethernet0 MTU to 1501
Aug 10 00:51:19.881378 sonic INFO swss#/supervisord: portmgrd Error: mtu greater than device maximum.
Aug 10 00:51:19.881936 sonic ERR swss#portmgrd: :- main: Runtime error: /sbin/ip link set dev "Ethernet0" mtu "1501" :
Aug 10 00:51:20.577196 sonic INFO swss#supervisord 2021-08-10 00:51:20,576 INFO exited: portmgrd (exit status 255; not expected)
Aug 10 00:51:21.590176 sonic INFO swss#/supervisor-proc-exit-listener: Process 'portmgrd' exited unexpectedly. Terminating supervisor 'swss'
```

#### Output of `show version`:

```
root@sonic:~# show ver

SONiC Software Version: SONiC.master.25538-5e435e05a
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 5e435e05a
Build date: Mon Jul 26 15:32:45 UTC 2021
Built by: AzDevOps@sonic-build-workers-000J8D

Platform: x86_64-accton_as7816_64x-r0
HwSKU: Accton-AS7816-64X
ASIC: broadcom
ASIC Count: 1
Serial Number: None
Model Number: None
Hardware Revision: None
Uptime: 01:00:15 up 28 min,  2 users,  load average: 0.00, 0.28, 0.50
```

#### Additional information you deem important (e.g. issue happens only occasionally):
This issue is fixed by https://github.com/Azure/sonic-buildimage/pull/3895 before, but the modification is removed after https://github.com/Azure/sonic-buildimage/pull/6526 merged.

**Comment by gechiang** [comment] 2021-08-13 01:08
I am able to reproduce this.
Had a discussion with Mahesh about this issue and this change was removed at SAI 4.3 bring up time suggested by BRCM since there was some issue with port not able to come up.  
I am in the process of adding this change back to see if it addresses this issue while not causing the port not coming up issue.
I will then follow up with BRCM on this to get a final resolution.

**Comment by gechiang** [comment] 2021-08-13 20:51
@vincentchiang-ec I have added back this fix and validated that it addressed the issue.
Please help review the PR (https://github.com/Azure/sonic-buildimage/pull/8472)
Please refer to that PR for details on what was done and what is expected from BRCM team.
When the PR is merged and an image is available with the fix, please help re-evaluate and closet his issue if you are satisfied with the resolution.
Thanks!

**Closed** 2021-08-15 00:01 UTC
