### ISSUE TITLE
Portchannel doesn't take traffic after updated

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#8449] opened 2021-08-12 09:20 UTC
#### Description

```test_po_update``` was failing in recent nightly test. I did some investigation, and found that it's because Portchannel didn't work after being updated.

 ```PortChannel0001``` is up
```
admin@str-msn4600c-acs-02:~$ show int portchannel 
Flags: A - active, I - inactive, Up - up, Dw - Down, N/A - not available,
       S - selected, D - deselected, * - not synced
  No.  Team Dev         Protocol     Ports
-----  ---------------  -----------  ---------------------------
 0001  PortChannel0001  LACP(A)(Up)  Ethernet4(S) Ethernet0(S)
 0002  PortChannel0002  LACP(A)(Up)  Ethernet20(S) Ethernet16(S)
 0003  PortChannel0003  LACP(A)(Up)  Ethernet68(S) Ethernet64(S)
 0004  PortChannel0004  LACP(A)(Up)  Ethernet80(S) Ethernet84(S)
```
Route is as expected
```
admin@str-msn4600c-acs-02:~$ show ip route 10.0.0.1 
Routing entry for 10.0.0.0/31
  Known via "connected", distance 0, metric 0, best
  Last update 00:05:51 ago
  * directly connected, PortChannel0001
```
But ping is not reachable
```
admin@str-msn4600c-acs-02:~$ ping 10.0.0.1 
PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
^C
--- 10.0.0.1 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 23ms
```
#### Steps to reproduce the issue:
The issue can be reproed with following script
```
#!/bin/bash

sudo config portchannel  member del PortChannel0001 Ethernet0
sudo config portchannel  member del PortChannel0001 Ethernet4

sleep 5s

sudo config interface  ip remove PortChannel0001 10.0.0.0/31
sleep 5s
show int portchannel


sleep 30s

sudo config interface  ip add PortChannel0001 10.0.0.0/31
sudo config portchannel  member add PortChannel0001 Ethernet0
sudo config portchannel  member add PortChannel0001 Ethernet4

sleep 5s
show int portchannel
ping 10.0.0.1
```
The portchannel will come back after around 8 minutes.

#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.11
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 772c9bb4f3
Build date: Thu Jul 29 10:53:26 UTC 2021
Built by: AzDevOps@sonic-int-build-workers-0002DX

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: ACS-MSN4600C
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2023X22076
Uptime: 09:18:58 up 13 min,  2 users,  load average: 1.46, 0.96, 0.70

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-mlnx          20201231.11         ab6b6daa6807        951MB
docker-syncd-mlnx          latest              ab6b6daa6807        951MB
docker-teamd               20201231.11         4b18ce291dbf        412MB
docker-teamd               latest              4b18ce291dbf        412MB
docker-router-advertiser   20201231.11         ccdba9a47665        401MB
docker-router-advertiser   latest              ccdba9a47665        401MB
docker-platform-monitor    20201231.11         d012babb6bde        722MB
docker-platform-monitor    latest              d012babb6bde        722MB
docker-lldp                20201231.11         d84dc7af5257        441MB
docker-lldp                latest              d84dc7af5257        441MB
docker-dhcp-relay          20201231.11         b36c40793a6c        408MB
docker-dhcp-relay          latest              b36c40793a6c        408MB
docker-database            20201231.11         1033e7defcbf        401MB
docker-database            latest              1033e7defcbf        401MB
docker-orchagent           20201231.11         3b399dfdf412        430MB
docker-orchagent           latest              3b399dfdf412        430MB
docker-sonic-telemetry     20201231.11         7d6bda508ef7        491MB
docker-sonic-telemetry     latest              7d6bda508ef7        491MB
docker-snmp                20201231.11         b79a9e321176        443MB
docker-snmp                latest              b79a9e321176        443MB
docker-fpm-frr             20201231.11         e4ca59344d40        430MB
docker-fpm-frr             latest              e4ca59344d40        430MB
docker-mux                 20201231.11         2a78814244c3        454MB
docker-mux                 latest              2a78814244c3        454MB
docker-sonic-restapi       20201231.11         81a08deda780        352MB
docker-sonic-restapi       latest              81a08deda780        352MB
docker-acms                20201231.11         d1102446ecbe        197MB
docker-acms                latest              d1102446ecbe        197MB
k8s.gcr.io/pause           3.4.1               0f8457a4c2ec        683kB
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by judyjoseph** [comment] 2021-08-18 06:40
@bingwang-ms Are you seeing this issue consistent ? I did try with 20201231.15 and it was ok - didn't see this behavior. 
Can you check, else share the device details where you see the issue, would like to take a look at logs.

**Comment by bingwang-ms** [comment] 2021-09-01 02:23
Yes. The failure is consistent on SN4600 testbed.

**Comment by prsunny** [comment] 2021-09-16 16:13
@volodymyrsamotiy to check

**Comment by bingwang-ms** [comment] 2021-09-18 08:36
The issue can be reproed on 20201231.28. Please find more details in attached syslog
[syslog.tar.gz](https://github.com/Azure/sonic-buildimage/files/7189561/syslog.tar.gz)
.

**Comment by volodymyrsamotiy** [comment] 2021-09-27 16:07
@bingwang-ms, I am not able to reproduce the issue.

I tried to run ```test_po_update``` 10 times and it always passed.

Also tried to run provided script 10 times as well and it never took minutes to get up:
* There are some sleep steps in the script so if run it as is then it takes about 40 seconds from the moment when ping stopped working and to the moment when it started working again.
* With removed sleep steps it takes 7-8 seconds.

Please note that I tried on the same platform (SN4600) and some old (from June) and latest 202012 images.

* So it could be something with the environment (e.g. maybe neighbor device is taking time to bring up).
Could you please double check to make sure it is not environment/testbed issues?
* Also could you please provide public commit hash that was used to build an image on which you faced this issue?
So I will build same image and check, in order to make sure that it is not the issue that was only on that specific version.

**Comment by bingwang-ms** [comment] 2021-09-29 07:44
@volodymyrsamotiy Thanks for the response.
I still can repro the issue on lattest image
```
SONiC Software Version: SONiC.master.40164-144b9f158
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 144b9f158
Build date: Tue Sep 28 13:52:43 UTC 2021
Built by: AzDevOps@sonic-build-workers-000QNI
```
And I also found that the when the issue happened, the traffic become unidirectional, that is the ICMP packet can't arrive at the neighbor, but the ICMP from the neighbor can arrive the DUT. 
Please find below the syslog.
The PortChannel members are add back at ```07:24:17.062261```, and the PortChannel didn't egress packet until ```07:31:40.445245 ```

**Comment by volodymyrsamotiy** [comment] 2024-03-19 15:09
Currently I see that "test_po_update" test is passing and even when issue was reported I wasn't able to reproduce so it could be some test infra issue for example.
So looks like this issue is not relevant anymore.
In case you see the same problem again please reopen the issue but for now I am closing this ticket.

**Closed as completed by volodymyrsamotiy** 2024-03-19 15:09 UTC
