### ISSUE TITLE
Command not working "show system-health detail"

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6463] opened 2021-01-15 10:33 UTC
Description
Command "show system-health detail" not working on the image from master based on "7fc2d381a98c73ffbc6668c9800b07f50b4d9c04" from Jan 05.

Steps to reproduce the issue

    Try to run the command:
    show system-health detail

**Describe the results you received**
```
show system-health detail 

System status summary

  System status LED  red
  Services:
    Status: OK
  Hardware:
    Status: Not OK
    Reasons: PSU 2 is out of power
             psu_2_fan_1 is missing
             Failed to perform health check for ServiceChecker due to exception - AttributeError("'NoneType' object has no attribute 'strip'")

System services and devices monitor list

Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 151, in detail
    entry.append(element[1]['type'])
KeyError: 'type'
```

**Describe the results you expected**
Command "show system-health detail" should work correctly.

**Output of show version**

Image from master based on "7fc2d381a98c73ffbc6668c9800b07f50b4d9c04" from Jan 05

```
SONiC Software Version: SONiC.app.ext.1
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 6e183434
Build date: Tue Jan 12 19:48:43 UTC 2021
Built by: stepanb@r-build-sonic03

Platform: x86_64-mlnx_msn4700-r0
HwSKU: ACS-MSN4700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2015X25486
Uptime: 10:08:46 up 20 min, 2 users, load average: 0.13, 0.61, 0.52

Docker images:
REPOSITORY TAG IMAGE ID SIZE
docker-platform-monitor 1.0.0 92d791d3f5b3 671MB
docker-platform-monitor latest 92d791d3f5b3 671MB
docker-sonic-mgmt-framework 1.0.0 d6de12943ab0 604MB
docker-sonic-mgmt-framework latest d6de12943ab0 604MB
docker-sflow 1.0.0 1d6a0d4ba350 451MB
docker-sflow latest 1d6a0d4ba350 451MB
docker-syncd-mlnx 1.0.0 84283f29217e 535MB
docker-syncd-mlnx latest 84283f29217e 535MB
docker-snmp 1.0.0 04321a94b86a 431MB
docker-snmp latest 04321a94b86a 431MB
docker-fpm-frr 1.0.0 55bd6d44e83f 468MB
docker-fpm-frr latest 55bd6d44e83f 468MB
docker-lldp 1.0.0 e31c7e8399c8 430MB
docker-lldp latest e31c7e8399c8 430MB
docker-database 1.0.0 944d79e86b82 390MB
docker-database latest 944d79e86b82 390MB
docker-orchagent 1.0.0 a8794949b2b2 468MB
docker-orchagent latest a8794949b2b2 468MB
docker-sonic-telemetry 1.0.0 520c2f2a7296 465MB
docker-sonic-telemetry latest 520c2f2a7296 465MB
docker-nat 1.0.0 db9f8a2e74fe 453MB
docker-nat latest db9f8a2e74fe 453MB
docker-dhcp-relay 1.0.0 c814038596bb 397MB
docker-dhcp-relay latest c814038596bb 397MB
docker-router-advertiser 1.0.0 8ccf42be85b1 390MB
docker-router-advertiser latest 8ccf42be85b1 390MB
docker-teamd 1.0.0 282d0d286dac 450MB
docker-teamd latest 282d0d286dac 450MB
```

**Comment by vemulabalaji** [comment] 2021-01-19 10:42
Thought of updating this issue, in our case LED status also not displayed.

show system-health detail
show system-health monitor-list
show system-health summary 
-- All the three are reporting issue.

root@sonic:~# show system-health detail
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 84, in detail
    if os.environ["UTILITIES_UNIT_TESTING"] == "1":
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'UTILITIES_UNIT_TESTING'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/system_health.py", line 97, in detail
    from sonic_platform.chassis import Chassis
ModuleNotFoundError: No module named 'sonic_platform'
root@sonic:~#


root@sonic:~# show version

SONiC Software Version: SONiC.master.556-dirty-20210118.073607
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 9b2bc880
Build date: Mon Jan 18 07:47:56 UTC 2021
Built by: johnar@jenkins-worker-8

Platform: x86_64-accton_as7716_32x-r0
HwSKU: Accton-AS7716-32X
ASIC: broadcom
ASIC Count: 1
Serial Number: 771632X1716006
Uptime: 14:56:19 up  1:12,  1 user,  load average: 0.93, 0.96, 0.78

**Comment by vaibhavhd** [comment] 2021-01-20 16:23
@jleveque, it seems that these were the issues that were earlier fixed in other platforms. This time `Accton` is reporting missing `sonic_platform` module, and Mellanox has some Python2 to 3 issues.

**Comment by jleveque** [comment] 2021-01-20 18:28
The original issue was reported on a Mellanox SN4700. I don't have one available to test, but I was unable to reproduce the Mellanox issue on a SN2700 with the latest Master build.

It appears the Accton issue is due to the lack of a Python 3 sonic-platform package.

@jostar-yang, @Junchao-Mellanox: Can you please investigate the reported issues on your respective platforms?

**Comment by maksymbelei95** [comment] 2021-01-20 18:39
@jleveque,
I am currently investigating the issue. It reproduces on my SN2700.
```
admin@sonic:~$ show version

SONiC Software Version: SONiC.master.514-f99dbff7
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: f99dbff7
Build date: Thu Jan  7 11:32:16 UTC 2021
Built by: johnar@jenkins-worker-7

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2020T04280
Uptime: 20:36:13 up 9 days,  3:10,  1 user,  load average: 4.55, 5.16, 5.36

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-syncd-mlnx             latest                8537800d1c46        536MB
docker-syncd-mlnx             master.514-f99dbff7   8537800d1c46        536MB
docker-sflow                  latest                0a822def5cfe        452MB
docker-sflow                  master.514-f99dbff7   0a822def5cfe        452MB
docker-snmp                   latest                2069a95759c9        432MB
docker-snmp                   master.514-f99dbff7   2069a95759c9        432MB
docker-teamd                  latest                08b104d44f5b        451MB
docker-teamd                  master.514-f99dbff7   08b104d44f5b        451MB
docker-router-advertiser      latest                8cb6defab300        391MB
docker-router-advertiser      master.514-f99dbff7   8cb6defab300        391MB
docker-platform-monitor       latest                5276a7643b58        672MB
docker-platform-monitor       master.514-f99dbff7   5276a7643b58        672MB
docker-lldp                   latest                b246a382937e        431MB
docker-lldp                   master.514-f99dbff7   b246a382937e        431MB
docker-database               latest                01e9cf4ea8cf        391MB
docker-database               master.514-f99dbff7   01e9cf4ea8cf        391MB
docker-orchagent              latest                b0ef7ae5f9a4        468MB
docker-orchagent              master.514-f99dbff7   b0ef7ae5f9a4        468MB
docker-nat                    latest                33f3d25505eb        453MB
docker-nat                    master.514-f99dbff7   33f3d25505eb        453MB
docker-sonic-telemetry        latest                873eda70c348        465MB
docker-sonic-telemetry        master.514-f99dbff7   873eda70c348        465MB
docker-dhcp-relay             latest                90a1733f4c5d        397MB
docker-dhcp-relay             master.514-f99dbff7   90a1733f4c5d        397MB
docker-sonic-mgmt-framework   latest                c6b96579ad33        604MB
docker-sonic-mgmt-framework   master.514-f99dbff7   c6b96579ad33        604MB
docker-fpm-frr                latest                d71593b61940        468MB
docker-fpm-frr                master.514-f99dbff7   d71593b61940        468MB
```
Is it ok that I will continue checking the issue?

**Comment by jleveque** [comment] 2021-01-20 18:41
@maksymbelei95: Yes, please continue. Your help is appreciated! :)

**Comment by Junchao-Mellanox** [comment] 2021-01-21 02:06
@jleveque I cannot reproduce both issues on following version.

```
SONiC Software Version: SONiC.master.527-3a942fb5
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 3a942fb5
Build date: Wed Jan 20 11:22:04 UTC 2021
Built by: johnar@jenkins-worker-7

Platform: x86_64-mlnx_msn2700-r0
HwSKU: ACS-MSN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1822K07815
Uptime: 02:03:12 up 8 min,  1 user,  load average: 4.48, 3.78, 1.94

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-syncd-mlnx             latest                6b8101957847        538MB
docker-syncd-mlnx             master.527-3a942fb5   6b8101957847        538MB
docker-sflow                  latest                1aaa50277daf        405MB
docker-sflow                  master.527-3a942fb5   1aaa50277daf        405MB
docker-snmp                   latest                72c457b887c1        434MB
docker-snmp                   master.527-3a942fb5   72c457b887c1        434MB
docker-teamd                  latest                cab653ba04cc        404MB
docker-teamd                  master.527-3a942fb5   cab653ba04cc        404MB
docker-sonic-mgmt-framework   latest                53c1d8316fcb        609MB
docker-sonic-mgmt-framework   master.527-3a942fb5   53c1d8316fcb        609MB
docker-router-advertiser      latest                5db761429e76        394MB
docker-router-advertiser      master.527-3a942fb5   5db761429e76        394MB
docker-platform-monitor       latest                db7107415464        683MB
docker-platform-monitor       master.527-3a942fb5   db7107415464        683MB
docker-lldp                   latest                c8697240626b        434MB
docker-lldp                   master.527-3a942fb5   c8697240626b        434MB
docker-database               latest                6b2833368aad        394MB
docker-database               master.527-3a942fb5   6b2833368aad        394MB
docker-orchagent              latest                455386895773        422MB
docker-orchagent              master.527-3a942fb5   455386895773        422MB
docker-macsec                 latest                29c7c5629629        407MB
docker-macsec                 master.527-3a942fb5   29c7c5629629        407MB
docker-nat                    latest                665cdada1d05        407MB
docker-nat                    master.527-3a942fb5   665cdada1d05        407MB
docker-sonic-telemetry        latest                05fa3159c3e1        468MB
docker-sonic-telemetry        master.527-3a942fb5   05fa3159c3e1        468MB
docker-dhcp-relay             latest                339d67031159        401MB
docker-dhcp-relay             master.527-3a942fb5   339d67031159        401MB
docker-fpm-frr                latest                1ea76cb22bd7        421MB
docker-fpm-frr                master.527-3a942fb5   1ea76cb22bd7        421MB

```

For the original issue, I suppose it has been fixed by commit: https://github.com/Azure/sonic-buildimage/commit/2d77a36658867a4f39340f5fa4bc066dd38d13ef

**Comment by maksymbelei95** [comment] 2021-01-21 07:28
@jleveque, I confirm the comment of @Junchao-Mellanox. The issue has fixed by 2d77a36.
I have tested on my SN2700 with a local changes from 2d77a36, and the issue is not reproducing now:
```
admin@sonic:/$ sudo show system-health detail
System status summary

  System status LED  green
  Services:
    Status: OK
  Hardware:
    Status: Not OK
    Reasons: telemetry|dialout_client is not Status ok
             telemetry|telemetry is not Status ok
             routeCheck is not Status ok

System services and devices monitor list

Name                      Status    Type
------------------------  --------  ----------
routeCheck                Not OK    Program
telemetry|telemetry       Not OK    Program
telemetry|dialout_client  Not OK    Program
sonic                     OK        System
rsyslog                   OK        Process
root-overlay              OK        Filesystem
var-log                   OK        Filesystem
teamd|teamsyncd           OK        Program
teamd|teammgrd            OK        Program
syncd|syncd               OK        Program
swss|orchagent            OK        Program
swss|portsyncd            OK        Program
swss|neighsyncd           OK        Program
swss|fdbsyncd             OK        Program
swss|vrfmgrd              OK        Program
swss|vlanmgrd             OK        Program
swss|intfmgrd             OK        Program
swss|portmgrd             OK        Program
swss|buffermgrd           OK        Program
swss|nbrmgrd              OK        Program
swss|vxlanmgrd            OK        Program
swss|coppmgrd             OK        Program
swss|tunnelmgrd           OK        Program
snmp|snmpd                OK        Program
snmp|snmp_subagent        OK        Program
sflow|sflowmgrd           OK        Program
lldp|lldpd_monitor        OK        Program
lldp|lldp_syncd           OK        Program
lldp|lldpmgrd             OK        Program
database|redis_server     OK        Program
bgp|zebra                 OK        Program
bgp|fpmsyncd              OK        Program
bgp|bgpd                  OK        Program
bgp|staticd               OK        Program
bgp|bgpcfgd               OK        Program
bgp|bgpmon                OK        Program
ASIC                      OK        ASIC
fan1                      OK        Fan
fan2                      OK        Fan
fan3                      OK        Fan
fan4                      OK        Fan
fan5                      OK        Fan
fan6                      OK        Fan
fan7                      OK        Fan
fan8                      OK        Fan
psu_1_fan_1               OK        Fan
psu_2_fan_1               OK        Fan
PSU 1                     OK        PSU
PSU 2                     OK        PSU

System services and devices ignore list

Name         Status    Type
-----------  --------  ------
psu.voltage  Ignored   Device
```

**Comment by jleveque** [comment] 2021-01-21 20:45
@Junchao-Mellanox, @maksymbelei95: Thank you for your help confirming!

Since the original issue reported was specific to Mellanox platforms, I am going to close this issue. @vemulabalaji: If you are still having issues with the Accton platform, please create a new issue to track it.

**Closed by jleveque** 2021-01-21 20:45 UTC
Labels: Triaged

**Comment by gcupryn** [comment] 2021-02-02 09:35
Seeing similar issue with Arista box with Barefoot ASIC - https://github.com/Azure/sonic-buildimage/issues/6641
