### ISSUE TITLE
docker dhcp build failed.

### ISSUE THREAD

**Issue by sunnogo** [Azure/sonic-buildimage#1669] opened 2018-05-02 02:50 UTC
**Description**

docker-dhcp-relay build failed.

**Steps to reproduce the issue:**
1. make target/sonic-broadcom.bin

**Describe the results you received:**
docker image build failed.

**Describe the results you expected:**

docker image build successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
branch 201803, commit id 8572f84ea0f6054f1c0440511db6501d6f465cfd
 ```

    **Attach debug file `sudo generate_dump`:**

```
Fetched 19.5 MB in 4s (4643 kB/s)
Reading package lists...
 ---> caaea7089f2d
Removing intermediate container 733d5b53e400
Step 4/12 : COPY debs/isc-dhcp-common_4.3.3-6_amd64.deb debs/
 ---> c04c819133ba
Removing intermediate container 53842895daae
Step 5/12 : COPY debs/isc-dhcp-relay_4.3.3-6_amd64.deb debs/
 ---> 013b381c2ffa
Removing intermediate container 8c684f9c9e07
Step 6/12 : RUN dpkg_apt() { [ -f $1 ] && { dpkg -i $1 || apt-get -y install -f; } || return 1; }; dpkg_apt debs/isc-dhcp-common_4.3.3-6_amd64.deb
 ---> Running in d3e4f7a09ac2
(Reading database ... 14581 files and directories currently installed.)
Preparing to unpack .../isc-dhcp-common_4.3.3-6_amd64.deb ...
Unpacking isc-dhcp-common (4.3.3-6) over (4.3.1-6+deb8u3) ...
Setting up isc-dhcp-common (4.3.3-6) ...
 ---> 86452f7b49f4
Removing intermediate container d3e4f7a09ac2
Step 7/12 : RUN dpkg_apt() { [ -f $1 ] && { dpkg -i $1 || apt-get -y install -f; } || return 1; }; dpkg_apt debs/isc-dhcp-relay_4.3.3-6_amd64.deb
 ---> Running in a90fc03b05ca
Selecting previously unselected package isc-dhcp-relay.
(Reading database ... 14581 files and directories currently installed.)
Preparing to unpack .../isc-dhcp-relay_4.3.3-6_amd64.deb ...
Unpacking isc-dhcp-relay (4.3.3-6) ...
Setting up isc-dhcp-relay (4.3.3-6) ...
Generating /etc/default/isc-dhcp-relay...
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for systemd (215-17+deb8u7) ...
 ---> d874498b6bf3
Removing intermediate container a90fc03b05ca
Step 8/12 : RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y
 ---> Running in beede5550618
Reading package lists...
Building dependency tree...
Reading state information...
Reading package lists...
Building dependency tree...
Reading state information...
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 isc-dhcp-client : Depends: isc-dhcp-common (= 4.3.1-6+deb8u3) but 4.3.3-6 is installed
E: Unmet dependencies. Try using -f.
The command '/bin/sh -c apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y' returned a non-zero code: 100
[  FAIL LOG END  ] [ target/docker-dhcp-relay.gz ]
slave.mk:377: recipe for target 'target/docker-dhcp-relay.gz' failed
make: *** [target/docker-dhcp-relay.gz] Error 1
make: *** Waiting for unfinished jobs....
Makefile:82: recipe for target 'target/sonic-broadcom.bin' failed
make: *** [target/sonic-broadcom.bin] Error 2
```

**Comment by sunnogo** [comment] 2018-05-02 02:52
Why not using isc-dhcp-client from compile output debian package?

**Comment by fgggid** [comment] 2018-05-02 02:53
see #1659

**Comment by yangbashuang** [comment] 2018-05-02 02:54
maybe same as below:
https://github.com/Azure/sonic-buildimage/pull/1659
https://github.com/Azure/sonic-buildimage/pull/1666

**Comment by sunnogo** [comment] 2018-05-02 03:05
@yangbashuang @fgggid Thanks!

I have searched issue with "dhcp docker" before commit the new one. But no issues found.

**Comment by sunnogo** [comment] 2018-05-02 07:28
#1659 has a new issue.

There's a mistake in `rules/isc-dhcp.mk`。

## error log

```
$ cat target/debs/isc-dhcp-client_4.3.3-6_amd64.deb.log 
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/sonic/src/isc-dhcp'
# Remove any stale files
rm -rf ./isc-dhcp
# Clone isc-dhcp repo
git clone https://anonscm.debian.org/cgit/pkg-dhcp/isc-dhcp.git
pushd ./isc-dhcp
# Reset HEAD to the commit of the proper tag
# NOTE: Using "git checkout <tag_name>" here detaches our HEAD,
# which stg doesn't like, so we use this method instead
git reset --hard debian/4.3.3-6
# Apply patches
stg init
stg import -s ../patch/series
# Build source and Debian packages
dpkg-buildpackage -rfakeroot -b -us -uc -j24
popd
# Move the newly-built .deb packages to the destination directory
mv isc-dhcp-common_4.3.3-6_amd64.deb isc-dhcp-relay_4.3.3-6_amd64.deb isc-dhcp-client_4.3.3-6_amd64.deb /sonic/target/debs/
Cloning into 'isc-dhcp'...
warning: Duplicated ref: refs/remotes/origin/experimental
warning: Duplicated ref: refs/remotes/origin/master
warning: Duplicated ref: refs/remotes/origin/pristine-tar
warning: Duplicated ref: refs/remotes/origin/upstream
warning: Duplicated ref: refs/tags/debian/4.1.0-1
warning: Duplicated ref: refs/tags/debian/4.1.1-1
warning: Duplicated ref: refs/tags/debian/4.1.1-2
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-10
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-11
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-12
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-13
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-14
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-15
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-16
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-16.1
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-17
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-4
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-5
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-6
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-7
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-8
warning: Duplicated ref: refs/tags/debian/4.1.1-P1-9
warning: Duplicated ref: refs/tags/debian/4.2.2-1
warning: Duplicated ref: refs/tags/debian/4.2.2-2
warning: Duplicated ref: refs/tags/debian/4.2.2.dfsg.1-3
warning: Duplicated ref: refs/tags/debian/4.2.2.dfsg.1-4
warning: Duplicated ref: refs/tags/debian/4.2.2.dfsg.1-5
warning: Duplicated ref: refs/tags/debian/4.2.4-1
warning: Duplicated ref: refs/tags/debian/4.2.4-2
warning: Duplicated ref: refs/tags/debian/4.2.4-3
warning: Duplicated ref: refs/tags/debian/4.2.4-4
warning: Duplicated ref: refs/tags/debian/4.2.4-5
warning: Duplicated ref: refs/tags/debian/4.2.4-6
warning: Duplicated ref: refs/tags/debian/4.2.4-7
warning: Duplicated ref: refs/tags/debian/4.3.0+dfsg-1
warning: Duplicated ref: refs/tags/debian/4.3.0+dfsg-2
warning: Duplicated ref: refs/tags/debian/4.3.0a1-1
warning: Duplicated ref: refs/tags/debian/4.3.0a1-2
warning: Duplicated ref: refs/tags/debian/4.3.1-1
warning: Duplicated ref: refs/tags/debian/4.3.1-2
warning: Duplicated ref: refs/tags/debian/4.3.1-3
warning: Duplicated ref: refs/tags/debian/4.3.1-4
warning: Duplicated ref: refs/tags/debian/4.3.1-5
warning: Duplicated ref: refs/tags/debian/4.3.1-6
warning: Duplicated ref: refs/tags/debian/4.3.1_b1
warning: Duplicated ref: refs/tags/debian/4.3.2-1
warning: Duplicated ref: refs/tags/debian/4.3.3-1
warning: Duplicated ref: refs/tags/debian/4.3.3-2
warning: Duplicated ref: refs/tags/debian/4.3.3-3
warning: Duplicated ref: refs/tags/debian/4.3.3-5
warning: Duplicated ref: refs/tags/debian/4.3.3-6
warning: Duplicated ref: refs/tags/debian/4.3.3-7
warning: Duplicated ref: refs/tags/debian/4.3.3-8
warning: Duplicated ref: refs/tags/debian/4.3.3-9
warning: Duplicated ref: refs/tags/debian/4.3.4-1
warning: Duplicated ref: refs/tags/debian/4.3.5-1
warning: Duplicated ref: refs/tags/debian/4.3.5-2
warning: Duplicated ref: refs/tags/debian/4.3.5-3
warning: Duplicated ref: refs/tags/debian/4.3.5_b1-1
warning: Duplicated ref: refs/tags/debin/4.2.2.dfsg.1-4
warning: Duplicated ref: refs/tags/upstream/4.1.0
warning: Duplicated ref: refs/tags/upstream/4.1.1
warning: Duplicated ref: refs/tags/upstream/4.1.1-P1
warning: Duplicated ref: refs/tags/upstream/4.2.2
warning: Duplicated ref: refs/tags/upstream/4.2.4
warning: Duplicated ref: refs/tags/upstream/4.2.5-P1
warning: Duplicated ref: refs/tags/upstream/4.3.0
warning: Duplicated ref: refs/tags/upstream/4.3.0a1
warning: Duplicated ref: refs/tags/upstream/4.3.1
warning: Duplicated ref: refs/tags/upstream/4.3.2
warning: Duplicated ref: refs/tags/upstream/4.3.3
warning: Duplicated ref: refs/tags/upstream/4.3.4
warning: Duplicated ref: refs/tags/upstream/4.3.4_b1
warning: Duplicated ref: refs/tags/upstream/4.3.5
warning: Duplicated ref: refs/tags/upstream/4.3.5_b1
error: Untracked working tree file 'LICENSE' would be overwritten by merge.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

Makefile:10: recipe for target '/sonic/target/debs/isc-dhcp-common_4.3.3-6_amd64.deb' failed
make[1]: *** [/sonic/target/debs/isc-dhcp-common_4.3.3-6_amd64.deb] Error 128
make[1]: Leaving directory '/sonic/src/isc-dhcp'
```

## error reason

ISC_DHCP_COMMON and ISC_DHCP_CLIENT are added to SONIC_MAKE_DEBS. However ISC_DHCP_CLIENT must be a derived package, and we cannot run `src/isc-dhcp/Makefile` twice.

```makefile
# isc-dhcp packages

ISC_DHCP_VERSION = 4.3.3-6

export ISC_DHCP_VERSION

ISC_DHCP_COMMON = isc-dhcp-common_$(ISC_DHCP_VERSION)_amd64.deb
$(ISC_DHCP_COMMON)_SRC_PATH = $(SRC_PATH)/isc-dhcp
SONIC_MAKE_DEBS += $(ISC_DHCP_COMMON)

ISC_DHCP_CLIENT = isc-dhcp-client_$(ISC_DHCP_VERSION)_amd64.deb
$(ISC_DHCP_CLIENT)_SRC_PATH = $(SRC_PATH)/isc-dhcp
SONIC_MAKE_DEBS += $(ISC_DHCP_CLIENT)

ISC_DHCP_RELAY = isc-dhcp-relay_$(ISC_DHCP_VERSION)_amd64.deb
$(eval $(call add_derived_package,$(ISC_DHCP_COMMON),$(ISC_DHCP_RELAY),$(ISC_DHCP_CLIENT)))
```

## Solution

patch:

```patch
From 8e06f1a3082c3adb20e39e334301d1d32463ffd5 Mon Sep 17 00:00:00 2001
From: jeromesun <jeromesun@tencent.com>
Date: Wed, 2 May 2018 15:26:39 +0800
Subject: [PATCH] [ISC-DHCP] fix isc-dhcp-client compile issue

---
 rules/isc-dhcp.mk | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)

diff --git a/rules/isc-dhcp.mk b/rules/isc-dhcp.mk
index 37c775d..a8d684f 100644
--- a/rules/isc-dhcp.mk
+++ b/rules/isc-dhcp.mk
@@ -9,8 +9,9 @@ $(ISC_DHCP_COMMON)_SRC_PATH = $(SRC_PATH)/isc-dhcp
 SONIC_MAKE_DEBS += $(ISC_DHCP_COMMON)
 
 ISC_DHCP_CLIENT = isc-dhcp-client_$(ISC_DHCP_VERSION)_amd64.deb
-$(ISC_DHCP_CLIENT)_SRC_PATH = $(SRC_PATH)/isc-dhcp
-SONIC_MAKE_DEBS += $(ISC_DHCP_CLIENT)
+#$(ISC_DHCP_CLIENT)_SRC_PATH = $(SRC_PATH)/isc-dhcp
+#SONIC_MAKE_DEBS += $(ISC_DHCP_CLIENT)
+$(eval $(call add_derived_package,$(ISC_DHCP_COMMON),$(ISC_DHCP_CLIENT)))
 
 ISC_DHCP_RELAY = isc-dhcp-relay_$(ISC_DHCP_VERSION)_amd64.deb
-$(eval $(call add_derived_package,$(ISC_DHCP_COMMON),$(ISC_DHCP_RELAY),$(ISC_DHCP_CLIENT)))
+$(eval $(call add_derived_package,$(ISC_DHCP_COMMON),$(ISC_DHCP_RELAY)))
-- 
2.7.4
```

**Comment by jleveque** [comment] 2018-05-02 07:48
@sunnogo: I encountered the same error you posted above. This led me to track down the root cause which I have fixed in https://github.com/Azure/sonic-buildimage/pull/1666.

After we merge that PR, I will immediately revert https://github.com/Azure/sonic-buildimage/pull/1659.

**Closed** 2018-05-02 18:46 UTC
Labels: question
