### ISSUE TITLE
[reboot] Fail to start Arista early platform initialization

### ISSUE THREAD

**Issue by lolyu** [Azure/sonic-buildimage#6138] opened 2020-12-07 05:52 UTC
**Description**

**Steps to reproduce the issue:**
1. Upgrade a DUT(Arista7060) to the latest master image
```
admin@sonic:~$ sudo sonic_installer install http://<server_ip>/broadcom/public/sonic-aboot-broadcom.swi
```
2. Run `show version`
3. Restart `platform-arista-swss.service`

**Describe the results you received:**
* during reboot, there is an error:
```
[FAILED] Failed to start Arista early platform initialization.
See 'systemctl status platform-arista-swss.service' for details.
[   37.629895] rc.local[532]: + SONIC_CONFIG_DIR=/host/image-HEAD.101-3e717210/sonic-config
```
* `show version`
```
admin@sonic:~$ show version

SONiC Software Version: SONiC.HEAD.101-3e717210
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 3e717210
Build date: Sun Dec  6 20:04:24 UTC 2020
Built by: johnar@jenkins-worker-22

Platform: x86_64-arista_7060_cx32s
HwSKU: Arista-7060CX-32S-C32
ASIC: broadcom
ASIC Count: 1
Traceback (most recent call last):
  File "/usr/local/bin/decode-syseeprom", line 171, in <module>
    exit(main())
  File "/usr/local/bin/decode-syseeprom", line 58, in main
    run(t, opts, args, support_eeprom_db)
  File "/usr/local/bin/decode-syseeprom", line 117, in run
    e = target.read_eeprom()
  File "/usr/lib/python3/dist-packages/arista/utils/sonic_eeprom.py", line 34, in read_eeprom
    return readPrefdl()
  File "/usr/lib/python3/dist-packages/arista/core/platform.py", line 54, in readPrefdl
    pfdl = Prefdl.fromTextFile(host_prefdl_path)
  File "/usr/lib/python3/dist-packages/arista/core/prefdl.py", line 237, in fromTextFile
    key, value = line.split(': ', 1)
ValueError: not enough values to unpack (expected 2, got 1)
Serial Number:
Uptime: 05:35:01 up 1 min,  1 user,  load average: 2.52, 0.75, 0.26

Docker images:
REPOSITORY                    TAG                 IMAGE ID            SIZE
docker-sonic-telemetry        HEAD.101-3e717210   cd6a12cca9ee        518MB
docker-sonic-telemetry        latest              cd6a12cca9ee        518MB
docker-snmp                   HEAD.101-3e717210   8daa11cbf19b        484MB
docker-snmp                   latest              8daa11cbf19b        484MB
docker-teamd                  HEAD.101-3e717210   e442c7202130        491MB
docker-teamd                  latest              e442c7202130        491MB
docker-sonic-mgmt-framework   HEAD.101-3e717210   2a3949717681        606MB
docker-sonic-mgmt-framework   latest              2a3949717681        606MB
docker-router-advertiser      HEAD.101-3e717210   2ded3ce86035        448MB
docker-router-advertiser      latest              2ded3ce86035        448MB
docker-platform-monitor       HEAD.101-3e717210   59987ecb8c7e        572MB
docker-platform-monitor       latest              59987ecb8c7e        572MB
docker-lldp                   HEAD.101-3e717210   079b876a59a1        488MB
docker-lldp                   latest              079b876a59a1        488MB
docker-dhcp-relay             HEAD.101-3e717210   c62a5faa21f1        455MB
docker-dhcp-relay             latest              c62a5faa21f1        455MB
docker-database               HEAD.101-3e717210   035f87ff4fcc        448MB
docker-database               latest              035f87ff4fcc        448MB
docker-orchagent              HEAD.101-3e717210   433129065bf0        505MB
docker-orchagent              latest              433129065bf0        505MB
docker-nat                    HEAD.101-3e717210   cc2ed184bfb5        494MB
docker-nat                    latest              cc2ed184bfb5        494MB
docker-fpm-frr                HEAD.101-3e717210   c13f136a82d1        507MB
docker-fpm-frr                latest              c13f136a82d1        507MB
docker-sflow                  HEAD.101-3e717210   28b7bad1411c        492MB
docker-sflow                  latest              28b7bad1411c        492MB
docker-syncd-brcm             HEAD.101-3e717210   a3c3d4b1837b        542MB
docker-syncd-brcm             latest              a3c3d4b1837b        542MB
```
* after `systemctl restart platform-arista-swss.service`, logs in `syslog`:
```
Dec  7 05:48:54.669149 sonic INFO arista[8723]: Traceback (most recent call last):
Dec  7 05:48:54.669365 sonic INFO arista[8723]:   File "/usr/bin/arista", line 8, in <module>
Dec  7 05:48:54.669541 sonic INFO arista[8723]:     sys.exit(main(sys.argv[1:]))
Dec  7 05:48:54.669657 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/cli/__init__.py", line 82, in main
Dec  7 05:48:54.669772 sonic INFO arista[8723]:     root.runAction(CliContext(), args)
Dec  7 05:48:54.669905 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/cli/parser.py", line 77, in runAction
Dec  7 05:48:54.670018 sonic INFO arista[8723]:     child.runAction(ctx, args, *others, **kwargs)
Dec  7 05:48:54.670132 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/cli/parser.py", line 64, in runAction
Dec  7 05:48:54.670246 sonic INFO arista[8723]:     self._runAction(self.action, ctx, args, *others, **kwargs)
Dec  7 05:48:54.670414 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/cli/parser.py", line 51, in _runAction
Dec  7 05:48:54.670528 sonic INFO arista[8723]:     ret = action.func(ctx, args, *others, **kwargs)
Dec  7 05:48:54.670642 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/cli/actions/default.py", line 26, in doDefaultPlatform
Dec  7 05:48:54.670756 sonic INFO arista[8723]:     platform = getPlatform(args.platform)
Dec  7 05:48:54.670867 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/platform.py", line 132, in getPlatform
Dec  7 05:48:54.670995 sonic INFO arista[8723]:     platformCls = getPlatformCls(name)
Dec  7 05:48:54.671107 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/platform.py", line 115, in getPlatformCls
Dec  7 05:48:54.671219 sonic INFO arista[8723]:     return detectPlatform()
Dec  7 05:48:54.671332 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/platform.py", line 94, in detectPlatform
Dec  7 05:48:54.671445 sonic INFO arista[8723]:     getSysEeprom()
Dec  7 05:48:54.671556 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/platform.py", line 74, in getSysEeprom
Dec  7 05:48:54.671666 sonic INFO arista[8723]:     syseeprom = getPrefdlData()
Dec  7 05:48:54.671778 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/utils.py", line 480, in funcWrapper
Dec  7 05:48:54.671889 sonic INFO arista[8723]:     return func(*args, **kwargs)
Dec  7 05:48:54.672028 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/platform.py", line 69, in getPrefdlData
Dec  7 05:48:54.672157 sonic INFO arista[8723]:     return readPrefdl().data()
Dec  7 05:48:54.672270 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/platform.py", line 54, in readPrefdl
Dec  7 05:48:54.672381 sonic INFO arista[8723]:     pfdl = Prefdl.fromTextFile(host_prefdl_path)
Dec  7 05:48:54.672493 sonic INFO arista[8723]:   File "/usr/lib/python3/dist-packages/arista/core/prefdl.py", line 237, in fromTextFile
Dec  7 05:48:54.672604 sonic INFO arista[8723]:     key, value = line.split(': ', 1)
Dec  7 05:48:54.672715 sonic INFO arista[8723]: ValueError: not enough values to unpack (expected 2, got 1)
``` 

**Describe the results you expected:**
* Arista early platform initialization should start without errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by vaibhavhd** [comment] 2020-12-07 17:08
@Staphylo is this bug related to the recent platform/eeprom/python2 to 3 changes?

FWIW, I think this is a 7060 only issue as I did not observe this issue on 7260. Thanks.

**Comment by Staphylo** [comment] 2020-12-07 17:54
Thanks for reporting this issue Vaibhav.
Could you provide the output of `cat -e /etc/sonic/.syseeprom`?
This issue is more likely tied to a refactor I did recently but not related to the python3 update.

**Comment by Staphylo** [comment] 2020-12-07 21:16
Independently of the output, I enhanced the robustness of the eeprom parser which should now gracefully handle misformated files.
I will publish a PR soon and tag this issue once it's up.
Nevertheless it would still be interesting to see the content of the eeprom cache and which value seems corrupted.

**Comment by vaibhavhd** [comment] 2020-12-07 21:21
Thanks Samuel! There is actually no `.syseeprom` file in the 7060 device.

```
root@sonic:/etc/sonic# cat -e /etc/sonic/.syseeprom
cat: /etc/sonic/.syseeprom: No such file or directory
root@sonic:/etc/sonic# 
root@sonic:/etc/sonic# 
root@sonic:/etc/sonic# ls -al
total 43
drwxr-xr-x 1 root root  4096 Dec  2 03:08 .
drwxr-xr-x 1 root root  4096 Dec  2 03:23 ..
-rw-r--r-- 1 root root    41 Nov 27 07:12 asic_config_checksum
-rw-r--r-- 1 root root 15958 Dec  2 03:08 config_db.json
-rw-r--r-- 1 root root  1456 Nov 27 07:18 constants.yml
-rw-r--r-- 1 root root  2169 Dec  2 03:08 copp_cfg.json
-rw------- 1 root root   403 Nov 27 07:17 core_analyzer.rc.json
drwxr-x--- 1  300  300  4096 Dec  2 03:08 frr
-rw-r--r-- 1 root root   588 Nov 27 07:26 generated_services.conf
-rw-r--r-- 1 root root  5850 Nov 27 07:18 init_cfg.json
-rw-r--r-- 1 root root    47 Nov 27 07:18 snmp.yml
-rw-r--r-- 1 root root   230 Nov 27 07:12 sonic_version.yml
-rw-r--r-- 1 root root    14 Nov 27 07:18 updategraph.conf
root@sonic:/etc/sonic#
```

**Comment by Staphylo** [comment] 2020-12-07 21:32
Could you also tell me if you see any of these files?
```
/host/.system-prefdl
/host/.system-prefdl-bin
```

**Comment by vaibhavhd** [comment] 2020-12-07 21:34
> Could you also tell me if you see any of these files?
> 
> ```
> /host/.system-prefdl
> /host/.system-prefdl-bin
> ```

Sure:
```
admin@str2-7060cx-32s-29:/host$ ls -al
total 44
drwxrwxr-x 7 root   88 4096 Dec  7 21:21 .
drwxr-xr-x 1 root root 4096 Dec  7 21:23 ..
-rw-rw---- 1 root   88  108 Dec  7 21:20 boot-config
drwxr-xr-x 2 root root 4096 Dec  7 21:20 disk-img
drwxr-xr-x 7 root   88 4096 Dec  7 21:20 image-HEAD.101-3e717210
-rw-r--r-- 1 root   88  346 Dec  7 21:20 kernel-params-base
-rw-r--r-- 1 root   88  185 Dec  7 21:20 machine.conf
drwxr-xr-x 2 root root 4096 Dec  7 21:20 migration
drwxr-xr-x 3 root root 4096 Dec  7 21:20 reboot-cause
-rw-r--r-- 1 root   88  222 Dec  7 21:20 .system-prefdl
drwxr-xr-x 3 root root 4096 Dec  7 21:21 warmboot
admin@str2-7060cx-32s-29:/host$ cat .system-prefdl 
DataFormat: 0002
PCA: PCA0061510A2
SerialNumber: SSJ17213051
KVN: 111
ASY: ASY0171710B0
HwApi: 03.00
HwEpoch: 02.00
HwRev: 22.00
MacAddrBase: 28993aa266bc
MfgTime: 20170722150957
SID: Upperlake
SKU: DCS-7060CX-32S
HwApi: 
admin@str2-7060cx-32s-29:/host$ 
```

**Comment by Staphylo** [comment] 2020-12-07 21:48
Thank you for the outputs Vaibhav.
I now have the root cause of the problem. My fix will gracefully handle this case.

**Comment by anshuv-mfst** [comment] 2020-12-09 16:20
PR filed and merged. 
@Staphylo - Please ask Samuel to include this fix in his PR to auto-close the issue.

**Comment by Staphylo** [comment] 2020-12-09 17:11
Anshu, I couldn't link the issue to the PR as the field is immutable on my PR.
I edited my PR message by adding a `fixes` that reference this issue, but that didn't solve it either.

**Comment by anshuv-mfst** [comment] 2020-12-09 18:09
Closing issue as fix is merged.

**Closed by anshuv-mfst** 2020-12-09 18:09 UTC
Labels: Bug :bug:, Triaged
