### ISSUE TITLE
[DPB] Command not working "show interface breakout"

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6608] opened 2021-01-29 15:39 UTC
**Description**
Command "show interface breakout" not working - the output is traceback.

**Steps to reproduce the issue**
1) Issue a command:
```
show interface breakout
```
**Describe the results you received**
Command ended with traceback:
```
show int breakout
Traceback (most recent call last):
  File "/usr/local/bin/show", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/show/interfaces/__init__.py", line 135, in breakout
    config_db = ConfigDBConnector()
NameError: name 'ConfigDBConnector' is not defined
```

**Describe the results you expected**
The command should provide configured breakout modes of the interfaces;

**Output of show version**
```
SONiC Software Version: SONiC.dpb_qa_image.0-23134a64
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 23134a64
Build date: Fri Jan 15 08:52:11 UTC 2021
Built by: vadymh@r-build-sonic03

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1550X12437
Uptime: 15:35:08 up 40 min,  2 users,  load average: 3.48, 4.64, 4.43

Docker images:
REPOSITORY                    TAG                       IMAGE ID            SIZE
docker-syncd-mlnx             dpb_qa_image.0-23134a64   72cd4f0bad6c        540MB
docker-syncd-mlnx             latest                    72cd4f0bad6c        540MB
docker-sflow                  dpb_qa_image.0-23134a64   070e94ad45b1        465MB
docker-sflow                  latest                    070e94ad45b1        465MB
docker-snmp                   dpb_qa_image.0-23134a64   4513d9bbede9        436MB
docker-snmp                   latest                    4513d9bbede9        436MB
docker-dhcp-relay             dpb_qa_image.0-23134a64   e9f74defdbed        402MB
docker-dhcp-relay             latest                    e9f74defdbed        402MB
docker-teamd                  dpb_qa_image.0-23134a64   4432208a6469        463MB
docker-teamd                  latest                    4432208a6469        463MB
docker-nat                    dpb_qa_image.0-23134a64   b0f25765961f        466MB
docker-nat                    latest                    b0f25765961f        466MB
docker-router-advertiser      dpb_qa_image.0-23134a64   875949f0ef94        395MB
docker-router-advertiser      latest                    875949f0ef94        395MB
docker-platform-monitor       dpb_qa_image.0-23134a64   77567d9ce67c        683MB
docker-platform-monitor       latest                    77567d9ce67c        683MB
docker-lldp                   dpb_qa_image.0-23134a64   9bba135a3864        435MB
docker-lldp                   latest                    9bba135a3864        435MB
docker-database               dpb_qa_image.0-23134a64   ae8be589a33c        394MB
docker-database               latest                    ae8be589a33c        394MB
docker-sonic-mgmt-framework   dpb_qa_image.0-23134a64   9f7fe89d1421        608MB
docker-sonic-mgmt-framework   latest                    9f7fe89d1421        608MB
docker-orchagent              dpb_qa_image.0-23134a64   5928b24d51e3        481MB
docker-orchagent              latest                    5928b24d51e3        481MB
docker-macsec                 dpb_qa_image.0-23134a64   b255f6b0ccf1        466MB
docker-macsec                 latest                    b255f6b0ccf1        466MB
docker-sonic-telemetry        dpb_qa_image.0-23134a64   4e502f1867fd        469MB
docker-sonic-telemetry        latest                    4e502f1867fd        469MB
docker-fpm-frr                dpb_qa_image.0-23134a64   684115a1f6cc        480MB
docker-fpm-frr                latest                    684115a1f6cc        480MB
[sonic_dump_r-qa-sw-eth-53_20210129_153634.tar.gz](https://github.com/Azure/sonic-buildimage/files/5894711/sonic_dump_r-qa-sw-eth-53_20210129_153634.tar.gz)

```

**Comment by dmytroxshevchuk** [comment] 2021-02-02 09:12
duplicate of https://github.com/Azure/sonic-buildimage/issues/5343
please see fix in PR: https://github.com/Azure/sonic-utilities/pull/1198 , merged into sonic-utilities, so issue must be resolved after update submodule.

**Comment by zhenggen-xu** [comment] 2021-02-10 17:13
https://github.com/Azure/sonic-buildimage/pull/6681

**Closed by zhenggen-xu** 2021-02-10 17:13 UTC
Labels: Port Breakout :trident:
