### ISSUE TITLE
[202012] Fail to program configurable drop counters: "create status: SAI_STATUS_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#8031] opened 2021-06-30 20:07 UTC
#### Steps to reproduce the issue:
1. Install latest of 202012 image on dualtor testbed
2. Via CLI, issue cmd: `config dropcounters install TEST PORT_INGRESS_DROPS L3_EGRESS_LINK_DOWN`
3. Check syslog for errors

#### Describe the results you received:
```
Jun 30 19:36:28.298410 str2-7050cx3-acs-09 NOTICE swss#orchagent: :- addDropReason: Added drop reason L3_EGRESS_LINK_DOWN to drop counter TEST
Jun 30 19:36:28.301474 str2-7050cx3-acs-09 ERR syncd#syncd: [none] SAI_API_DEBUG_COUNTER:_brcm_sai_port_in_drop_reasons_apply:894 Out of port rx counter resources.
Jun 30 19:36:28.301751 str2-7050cx3-acs-09 ERR syncd#syncd: [none] SAI_API_DEBUG_COUNTER:brcm_sai_create_debug_counter:295 applying drop reason failed with error -4.
Jun 30 19:36:28.301751 str2-7050cx3-acs-09 ERR swss#orchagent: :- create: create status: SAI_STATUS_INSUFFICIENT_RESOURCES
Jun 30 19:36:28.301908 str2-7050cx3-acs-09 ERR swss#orchagent: :- addDebugCounterToSAI: Failed to create debug counter 'TEST'
Jun 30 19:36:28.302038 str2-7050cx3-acs-09 ERR swss#orchagent: :- doTask: Failed to create debug counter 'TEST'
Jun 30 19:36:28.302038 str2-7050cx3-acs-09 ERR syncd#syncd: :- sendApiResponse: api SAI_COMMON_API_CREATE failed in syncd mode: SAI_STATUS_INSUFFICIENT_RESOURCES
Jun 30 19:36:28.302193 str2-7050cx3-acs-09 ERR swss#orchagent: :- doTask: Failed to process debug counters 'SET' task, error(s) occurred during execution
Jun 30 19:36:28.302324 str2-7050cx3-acs-09 ERR syncd#syncd: :- processQuadEvent: attr: SAI_DEBUG_COUNTER_ATTR_TYPE: SAI_DEBUG_COUNTER_TYPE_PORT_IN_DROP_REASONS
Jun 30 19:36:28.302324 str2-7050cx3-acs-09 ERR syncd#syncd: :- processQuadEvent: attr: SAI_DEBUG_COUNTER_ATTR_IN_DROP_REASON_LIST: 1:SAI_IN_DROP_REASON_L3_EGRESS_LINK_DOWN
```

#### Describe the results you expected:
Drop counters should be configurable, and no errors should be seen.

#### Output of `show version`:

```
SONiC Software Version: SONiC.20201231.06
Distribution: Debian 10.10
Kernel: 4.19.0-12-2-amd64
Build commit: 959975cede
Build date: Sat Jun 26 14:32:47 UTC 2021
Built by: sonicbld@new-worker-20

Platform: x86_64-arista_7050cx3_32s
HwSKU: Arista-7050CX3-32S-D48C8
ASIC: broadcom
ASIC Count: 1
```

SAI version:
```
Package: libsaibcm
Status: install ok installed
Priority: extra
Section: libs
Installed-Size: 242329
Maintainer: Guohan Lu <gulv@microsoft.com>
Architecture: amd64
Source: saibcm
Version: 4.3.3.8-1
Provides: libsai
```

#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by vaibhavhd** [comment] 2021-06-30 20:16
This issue has been failing the `test_configurable_drop_counters`

**Comment by vaibhavhd** [comment] 2021-06-30 20:43
The error was also seen on older image 202012.02, SAI 4.3.3.5-3

**Comment by prsunny** [comment] 2021-06-30 23:16
L3_EGRESS_LINK_DOWN is part of the capabilities. Should ideally be supported.

**Comment by vaibhavhd** [comment] 2021-07-01 16:24
@prsunny, @gechiang should we raise a CSP with Broadcom for this?

**Comment by gechiang** [comment] 2021-07-01 16:27
I will open a CSP for this. Thanks!

**Comment by gechiang** [comment] 2021-07-01 16:28
@vaibhavhd Is this only failing for TD3 platform and not seen on other BRCM based platforms such as S6100, 7260CX3, DX010,... etc?

**Comment by gechiang** [comment] 2021-07-01 17:18
On S6100 and 7260 no issue found when same command issued:
```
admin@str-s6100-acs-2:~$ sudo config dropcounters install TEST PORT_INGRESS_DROPS L3_EGRESS_LINK_DOWN
admin@str-s6100-acs-2:~$
admin@str-s6100-acs-2:~$
admin@str-s6100-acs-2:~$ sudo tail -F /var/log/syslog
Jul 1 17:10:55.319229 str-s6100-acs-2 NOTICE acms#root: message repeated 4 times: [ Waiting for bootstrap cert]
Jul 1 17:11:17.610771 str-s6100-acs-2 INFO swss#/supervisord: arp_update ping6: Warning: source address might be selected on device other than PortChannel0001.
Jul 1 17:11:17.621705 str-s6100-acs-2 INFO swss#/supervisord: arp_update ping6: Warning: source address might be selected on device other than PortChannel0002.
Jul 1 17:11:17.637252 str-s6100-acs-2 INFO swss#/supervisord: arp_update ping6: Warning: source address might be selected on device other than PortChannel0003.
Jul 1 17:11:17.653318 str-s6100-acs-2 INFO swss#/supervisord: arp_update ping6: Warning: source address might be selected on device other than PortChannel0004.
Jul 1 17:11:17.683831 str-s6100-acs-2 INFO swss#/supervisord: arp_update ping6: Warning: source address might be selected on device other than Vlan1000.
Jul 1 17:11:55.325087 str-s6100-acs-2 NOTICE acms#root: Waiting for bootstrap cert
Jul 1 17:12:19.159750 str-s6100-acs-2 NOTICE swss#orchagent: :- addDropReason: Added drop reason L3_EGRESS_LINK_DOWN to drop counter TEST
Jul 1 17:12:19.261103 str-s6100-acs-2 NOTICE swss#orchagent: :- reconcileFreeDropCounters: Successfully matched drop reasons to counter TEST
Jul 1 17:12:19.261288 str-s6100-acs-2 NOTICE swss#orchagent: :- installDebugCounter: Successfully created drop counter TEST
^C
admin@str-s6100-acs-2:~$

Jun 30 23:28:20.830562 str-7260cx3-acs-2 INFO ansible-command: Invoked with creates=None executable=None _uses_shell=False strip_empty_ends=True _raw_params=config dropcounters install TEST PORT_INGRESS_DROPS L3_EGRESS_LINK_DOWN removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
Jun 30 23:28:21.171333 str-7260cx3-acs-2 NOTICE swss#orchagent: :- addDropReason: Added drop reason L3_EGRESS_LINK_DOWN to drop counter TEST
Jun 30 23:28:21.214697 str-7260cx3-acs-2 NOTICE swss#orchagent: :- reconcileFreeDropCounters: Successfully matched drop reasons to counter TEST
Jun 30 23:28:21.214697 str-7260cx3-acs-2 NOTICE swss#orchagent: :- installDebugCounter: Successfully created drop counter TEST
```

**Comment by gechiang** [comment] 2021-07-01 17:28
BRCM Case CS00012197146 filed

**Comment by gechiang** [comment] 2021-07-01 20:00
manually re-ran the offending testcase but this time it seems to not have caused the error...
We need to figure out if any other prior testcase run may be required before hitting this issue...
Will lower the BRCM case priority till we get more details on it.

**Comment by gechiang** [comment] 2021-09-30 02:26
@vaibhavhd Can you Try the latest 202012 image which should have the fix for this issue to see if it is still reproducible?
If not, we can proceed to close this issue.
Thanks!

**Comment by gechiang** [comment] 2021-12-20 23:28
It looks like it is fixed in 202012 branch.
@vaibhavhd if you see it again, feel free to reopen this issue.

Closing it...

**Closed by gechiang** 2021-12-20 23:28 UTC
Labels: brcmsai, Issues for 202012, Dual ToR Platform :gemini:
