### ISSUE TITLE
[yang] Scheduler Yang models do not support "scheduler.0" value

### ISSUE THREAD

**Issue by alexrallen** [Azure/sonic-buildimage#9800] opened 2022-01-19 18:27 UTC
When a scheduler is defined in the following way....

```
    "SCHEDULER": {
        "scheduler.0": {
            "type": "DWRR",
            "weight": "14"
        },
        "scheduler.1": {
            "type": "DWRR",
            "weight": "15"
        }
    },
```

We see dynamic port breakout fail in the following manner...

```
libyang[0]: Value "scheduler.0" does not satisfy the constraint "[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})|[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})([@]{1})([0-9]{1,3})" (range, length, or pattern). (path: /sonic-scheduler:sonic-scheduler/SCHEDULER/SCHEDULER_LIST[name='scheduler.0']/name)

sonic_yang(3):Data Loading Failed:Value "scheduler.0" does not satisfy the constraint "[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})|[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})([@]{1})([0-9]{1,3})" (range, length, or pattern).

Data Loading Failed

Value "scheduler.0" does not satisfy the constraint "[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})|[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})([@]{1})([0-9]{1,3})" (range, length, or pattern).
```

 This is due to the following constraint defined by the scheduler yang model which is too restrictive

```
leaf name {

    type string {
        pattern "[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})|[a-zA-Z0-9]{1}([-a-zA-Z0-9_]{0,31})([@]{1})([0-9]{1,3})";
        length 1..36 {
            error-message "Invalid length for scheduler name.";
            error-app-tag scheduler-name-invalid-length;
        }
    }
    description "Scheduler name";
}
```

**Comment by zhangyanzhao** [comment] 2022-01-20 18:15
Venkat will follow up with Dell team.

**Comment by dgsudharsan** [comment] 2022-02-01 05:05
Should be fixed by https://github.com/Azure/sonic-buildimage/pull/9873

**Comment by venkatmahalingam** [comment] 2022-02-08 03:08
@alexrallen What's the latest status on this issue? hope the issue is fixed after Ashok's fix, please confirm, if the issue is fixed, please close the same.

**Closed** 2022-02-08 03:09 UTC
Labels: Triaged, yang, DELL
