### ISSUE TITLE
mlnx msn2010: default config_db.json generation with sonic-cfggen is not working

### ISSUE THREAD

**Issue by nikos-github** [Azure/sonic-buildimage#2236] opened 2018-11-08 06:34 UTC
admin@sonic: sudo sonic-cfggen -H -k ACS-MSN2010 --preset t1
Failed to get port config

**Comment by andriymoroz-mlnx** [comment] 2018-11-12 17:00
could be dependent on other issues you opened (corrupted output of platform info)
please show output of
`cat /host/machine.conf`
and
`cat /usr/share/sonic/device/x86_64-mlnx_msn2010-r0/ACS-MSN2010/port_config.ini`

**Comment by nikos-github** [comment] 2018-11-12 17:47
@andriymoroz-mlnx Will get back to you on this in a couple of hours.

**Comment by mykolaf** [comment] 2018-11-15 14:57
@nikos-github  Did you look for port_config.ini? Based on the error it's either missing or sonic-cfggen is unable to parse it.

**Comment by mykolaf** [comment] 2018-11-26 08:47
Hi @nikos-github, this issue should also be fixed by ONIE upgrade. 
The cause is the same as https://github.com/Azure/sonic-utilities/issues/370 .
Could you confirm please?

**Closed** 2019-02-18 06:16 UTC
Labels: bug :bug:
