### ISSUE TITLE
[201811->202012][WARM] APPLY_VIEW failure and core seen in LAG member down scenario

### ISSUE THREAD

**Issue by vaibhavhd** [Azure/sonic-buildimage#10390] opened 2022-03-29 16:57 UTC
#### Description

Warmboot SAD case (dur_lag_member_down) causes APPLY_VIEW failure due to unwanted ASIC operations during APPLY_VIEW.

#### Steps to reproduce the issue:
1. Warm reboot from 201811 to latest 202012 with 1 or more LAG member down from DUT side.
2.
3.

#### Describe the results you received:

1. Object count for SAI_OBJECT_TYPE_LAG_MEMBER, SAI_OBJECT_TYPE_ROUTE_ENTRY on current view is different than on temporary view
2. Logs complain about failed to find best candidate for LAG using LAG member and port
3. Too many unwanted ASIC operations on SAI_OBJECT_TYPE_ROUTE_ENTRY, SAI_OBJECT_TYPE_LAG_MEMBER.
4. One of the REMOVE operations fail the APPLY_VIEW:
	SAI_API_NEIGHBOR:brcm_sai_remove_neighbor_entry:844 Neighbor vr_id 0 NH 1 references found.
	ASIC is in inconsistent state: :- asic_process_event: failed to execute api: remove, key: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"10.0.0.33","rif":"oid:0x60000000016d4","switch_id":"oid:0x21000000000000"}, status: 
5. This triggers syncd to send switch_shutdown_request to OA
6. OA does not takes this well, and hits GP, as a result of which coredump is generated.

LOGs:
```
Mar 29 11:04:44.529508 str-7260cx3-acs-2 INFO syncd#syncd: [none] SAI_API_SWITCH:brcm_sai_update_known_init_version:13844 WB upgrade from: 3.5.3.8 to 4.3.5.3


Mar 29 11:05:08.241580 str-7260cx3-acs-2 NOTICE syncd#syncd: :- checkInternalObjects: check internal objects
Mar 29 11:05:08.293475 str-7260cx3-acs-2 NOTICE syncd#syncd: :- createPreMatchMap: preMatch map size: 140, tmp oid obj: 1236
Mar 29 11:05:08.293475 str-7260cx3-acs-2 NOTICE syncd#syncd: :- createPreMatchMap: create preMatch map took 0.049940 sec
Mar 29 11:05:08.296737 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_ACL_TABLE on current view 3 is different than on temporary view: 2
Mar 29 11:05:08.296737 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_ACL_ENTRY on current view 2 is different than on temporary view: 0
Mar 29 11:05:08.296737 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_ACL_TABLE_GROUP on current view 244 is different than on temporary view: 116
Mar 29 11:05:08.296811 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_HOSTIF_TRAP_GROUP on current view 6 is different than on temporary view: 1
Mar 29 11:05:08.296811 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_POLICER on current view 3 is different than on temporary view: 0
Mar 29 11:05:08.298363 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_LAG_MEMBER on current view 2 is different than on temporary view: 8
Mar 29 11:05:08.298544 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_HOSTIF_TRAP on current view 12 is different than on temporary view: 1
Mar 29 11:05:08.302462 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count for SAI_OBJECT_TYPE_ROUTE_ENTRY on current view 12824 is different than on temporary view: 12818
Mar 29 11:05:08.302462 str-7260cx3-acs-2 WARNING syncd#syncd: :- logViewObjectCount: object count is different on both view, there will be ASIC OPERATIONS!
...

Mar 29 11:05:08.457574 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForLag: found temp LAG member oid:0x2000000001ae0 which uses temp LAG member oid:0x1b000000001ae4
Mar 29 11:05:08.457574 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForLag: failed to find best candidate for LAG using LAG member and port
Mar 29 11:05:08.458205 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForAclTableGroup: failed to find best candidate for ACL_TABLE_GROUP using port
Mar 29 11:05:08.521140 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForAclTableGroup: failed to find best candidate for ACL_TABLE_GROUP using port
Mar 29 11:05:08.521140 str-7260cx3-acs-2 WARNING syncd#syncd: :- findCurrentBestMatchForGenericObjectUsingHeuristic: heuristic failed for SAI_OBJECT_TYPE_ACL_TABLE_GROUP, selecting at random (count: 8, exact match: 2)
Mar 29 11:05:08.521140 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForLag: found temp LAG member oid:0x2000000001ae1 which uses temp LAG member oid:0x1b000000001ae6
Mar 29 11:05:08.521140 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForLag: failed to find best candidate for LAG using LAG member and port
Mar 29 11:05:08.521579 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForLag: found temp LAG member oid:0x2000000001ae2 which uses temp LAG member oid:0x1b000000001ae8
Mar 29 11:05:08.521579 str-7260cx3-acs-2 NOTICE syncd#syncd: :- findCurrentBestMatchForLag: failed to find best candidate for LAG using LAG member and port

...
Mar 29 11:05:09.019392 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: operations to execute on ASIC: 676
...

Mar 29 11:05:09.022077 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"10.0.0.32/31","switch_id":"oid:0x21000000000000","vr":"oid:0x300000000007c"}
Mar 29 11:05:09.022077 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"10.0.0.34/31","switch_id":"oid:0x21000000000000","vr":"oid:0x300000000007c"}
Mar 29 11:05:09.022077 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"10.0.0.36/31","switch_id":"oid:0x21000000000000","vr":"oid:0x300000000007c"}
Mar 29 11:05:09.022138 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"fc00::20/126","switch_id":"oid:0x21000000000000","vr":"oid:0x300000000007c"}
Mar 29 11:05:09.022138 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"fc00::24/126","switch_id":"oid:0x21000000000000","vr":"oid:0x300000000007c"}
Mar 29 11:05:09.022187 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"fc00::28/126","switch_id":"oid:0x21000000000000","vr":"oid:0x300000000007c"}
Mar 29 11:05:09.022187 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"10.0.0.33","rif":"oid:0x60000000016d4","switch_id":"oid:0x21000000000000"}
Mar 29 11:05:09.022215 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"10.0.0.35","rif":"oid:0x60000000016d5","switch_id":"oid:0x21000000000000"}
Mar 29 11:05:09.022237 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"10.0.0.37","rif":"oid:0x60000000016d6","switch_id":"oid:0x21000000000000"}
Mar 29 11:05:09.022270 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"fc00::22","rif":"oid:0x60000000016d4","switch_id":"oid:0x21000000000000"}
Mar 29 11:05:09.022291 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"fc00::26","rif":"oid:0x60000000016d5","switch_id":"oid:0x21000000000000"}
Mar 29 11:05:09.022313 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: remove: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"fc00::2a","rif":"oid:0x60000000016d6","switch_id":"oid:0x21000000000000"}
...
Mar 29 11:05:09.030894 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: create: SAI_OBJECT_TYPE_NEXT_HOP:oid:0x4000000001bd2
Mar 29 11:05:09.030894 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: - SAI_NEXT_HOP_ATTR_ROUTER_INTERFACE_ID oid:0x60000000016d6
Mar 29 11:05:09.030894 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: - SAI_NEXT_HOP_ATTR_TYPE SAI_NEXT_HOP_TYPE_IP
Mar 29 11:05:09.030928 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: - SAI_NEXT_HOP_ATTR_IP 10.0.0.33
Mar 29 11:05:09.030928 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: create: SAI_OBJECT_TYPE_NEXT_HOP:oid:0x4000000001bd3
Mar 29 11:05:09.030928 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: - SAI_NEXT_HOP_ATTR_ROUTER_INTERFACE_ID oid:0x60000000016d6
Mar 29 11:05:09.030928 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: - SAI_NEXT_HOP_ATTR_TYPE SAI_NEXT_HOP_TYPE_IP
Mar 29 11:05:09.030928 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: - SAI_NEXT_HOP_ATTR_IP fc00::22
...

Mar 29 11:05:09.050271 str-7260cx3-acs-2 ERR syncd#syncd: [none] SAI_API_NEIGHBOR:brcm_sai_remove_neighbor_entry:844 Neighbor vr_id 0 NH 1 references found.
Mar 29 11:05:09.050297 str-7260cx3-acs-2 ERR syncd#syncd: :- asic_process_event: failed to execute api: remove, key: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"10.0.0.33","rif":"oid:0x60000000016d4","switch_id":"oid:0x21000000000000"}, status: SAI_STATUS_OBJECT_IN_USE
Mar 29 11:05:09.050332 str-7260cx3-acs-2 NOTICE syncd#syncd: :- executeOperationsOnAsic: asic apply took 0.028692 sec
Mar 29 11:05:09.050353 str-7260cx3-acs-2 ERR syncd#syncd: :- executeOperationsOnAsic: Error while executing asic operations, ASIC is in inconsistent state: :- asic_process_event: failed to execute api: remove, key: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"10.0.0.33","rif":"oid:0x60000000016d4","switch_id":"oid:0x21000000000000"}, status: SAI_STATUS_OBJECT_IN_USE
Mar 29 11:05:09.192200 str-7260cx3-acs-2 NOTICE syncd#syncd: :- applyView: apply took 2.091120 sec
Mar 29 11:05:09.192449 str-7260cx3-acs-2 ERR syncd#syncd: :- run: Runtime error: :- asic_process_event: failed to execute api: remove, key: SAI_OBJECT_TYPE_NEIGHBOR_ENTRY:{"ip":"10.0.0.33","rif":"oid:0x60000000016d4","switch_id":"oid:0x21000000000000"}, status: SAI_STATUS_OBJECT_IN_USE
Mar 29 11:05:09.192449 str-7260cx3-acs-2 NOTICE syncd#syncd: :- sendShutdownRequest: sending switch_shutdown_request notification to OA for switch: oid:0x21000000000000
Mar 29 11:05:09.192627 str-7260cx3-acs-2 ERR swss#orchagent: :- syncd_apply_view: Failed to notify syncd APPLY_VIEW -1
Mar 29 11:05:09.192866 str-7260cx3-acs-2 ERR swss#orchagent: :- on_switch_shutdown_request: Syncd stopped
Mar 29 11:05:09.193210 str-7260cx3-acs-2 INFO swss#/supervisord: orchagent free(): corrupted unsorted chunks
Mar 29 11:05:09.193451 str-7260cx3-acs-2 INFO kernel: [   57.989969] traps: orchagent[2521] general protection ip:7f3f952d5d57 sp:7ffd36402330 error:0 in libc-2.28.so[7f3f952be000+148000]
Mar 29 11:05:09.193740 str-7260cx3-acs-2 NOTICE syncd#syncd: :- sendShutdownRequestAfterException: notification send successfully
Mar 29 11:05:09.733962 str-7260cx3-acs-2 INFO swss#supervisord 2022-03-29 11:05:09,733 INFO exited: orchagent (terminated by SIGSEGV (core dumped); not expected)
```

#### Output of `show version`:

```
WB upgrade from: 3.5.3.8 to 4.3.5.3
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

#### Additional information you deem important (e.g. issue happens only occasionally):

[syslog_dut_lag_member_down_3_3 (1).log](https://github.com/Azure/sonic-buildimage/files/8373543/syslog_dut_lag_member_down_3_3.1.log)
[Info logs, saidump,sairedis.zip](https://github.com/Azure/sonic-buildimage/files/8374553/Info.logs.saidump.sairedis.zip)

[saidump_201811_lagmemberdown_3.log](https://github.com/Azure/sonic-buildimage/files/8374563/saidump_201811_lagmemberdown_3.log)

**Comment by kcudnik** [comment] 2022-03-29 18:22
could you provide sairedis recording for this scenario ?

**Comment by kcudnik** [comment] 2022-03-29 18:23
SAI_OBJECT_TYPE_NEIGHBOR_ENTRY is a leaf objects and it don't have any dependencies, it should be possible to remove it at any time, i think we discuss this on last issue with lag members, and it needs to be fixed by vendor

**Comment by tjchadaga** [comment] 2022-03-29 20:55
> RY is a leaf objects and it don't have any dependencies, it should be possible to remove it at any time, i think we discuss this on last issue with lag members, and it needs to be fixed by vendor

CS00012228971 filed with broadcom is tracking this RFE

**Comment by kcudnik** [comment] 2022-03-29 22:22
issue is probably related to wrong matching RIF interfaces, which from syslog seems like wrong guess is taken, since rif interfaces based on lag which don't have lag members are exactly the same, so selection at random is performed. i will analyse attached logs and add pre match logic based on neighbor entry which will cause match rif interfaces

**Comment by kcudnik** [comment] 2022-03-30 15:59
@tjchadaga sairedis.rec you attached is from warm boot only, i need also part from cold boot on 201811, otherwise i wont be able to reproduce this

**Comment by kcudnik** [comment] 2022-03-30 17:33
possible fix is here: https://github.com/Azure/sonic-sairedis/pull/1026

**Comment by kcudnik** [comment] 2022-04-05 10:49
Fix for master and 202012 https://github.com/Azure/sonic-sairedis/pull/1027 has been merged

**Comment by prsunny** [comment] 2022-04-13 15:46
[Issue triage] @vaibhavhd, PRs are merged. Can you please check if this can be closed?

**Closed** 2022-06-16 19:27 UTC
Labels: warmboot :boot:, Triaged, Issues for 202012
