### ISSUE TITLE
warmboot  syncd pre shutdown fails in latest master and device hangs

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-buildimage#7094] opened 2021-03-18 10:22 UTC
#### Description

Warmboot fails in latest master and the device hangs from  master label # 601
Syncd pre-shutdown failed and the device hangs .
This issue is not seen in image # 600 

**Log:**

	root@sonic-10429:~# warm-reboot  -v
	Thu 18 Mar 2021 09:35:22 AM UTC Saving counters folder before warmboot...
	Thu 18 Mar 2021 09:35:23 AM UTC Pausing orchagent ...
	Thu 18 Mar 2021 09:35:23 AM UTC Collecting logs to check ssd health before warm-reboot...
	Thu 18 Mar 2021 09:35:24 AM UTC Stopping nat ...
	Dumping conntrack entries failed
	Error response from daemon: Cannot kill container: nat: No such container: nat
	Thu 18 Mar 2021 09:35:24 AM UTC Stopped nat ...
	Thu 18 Mar 2021 09:35:24 AM UTC Stopping radv service...
	Thu 18 Mar 2021 09:35:24 AM UTC Stopped radv service...
	Thu 18 Mar 2021 09:35:24 AM UTC Stopping bgp ...
	Thu 18 Mar 2021 09:35:28 AM UTC Stopped bgp ...
	Thu 18 Mar 2021 09:35:28 AM UTC Stopping sflow ...
	Thu 18 Mar 2021 09:35:28 AM UTC Stopped sflow ...
	Thu 18 Mar 2021 09:35:31 AM UTC Stopping swss service ...
	Thu 18 Mar 2021 09:35:39 AM UTC Stopped swss service ...
	Thu 18 Mar 2021 09:35:39 AM UTC Initialize pre-shutdown ...
	Thu 18 Mar 2021 09:35:40 AM UTC Stopping syncd docker
	Thu 18 Mar 2021 09:35:40 AM UTC Waiting for pre-shutdown ...
	Thu 18 Mar 2021 09:37:31 AM UTC Syncd pre-shutdown failed: requesting ...
	Thu 18 Mar 2021 09:37:31 AM UTC Backing up database ...
	Thu 18 Mar 2021 09:37:31 AM UTC Stopping teamd ...
	Thu 18 Mar 2021 09:37:38 AM UTC Stopped teamd ...
	Thu 18 Mar 2021 09:37:38 AM UTC Stopping syncd ...
	Thu 18 Mar 2021 09:37:38 AM UTC Stopped syncd ...
	Thu 18 Mar 2021 09:37:38 AM UTC Stopping all remaining containers ...
	Thu 18 Mar 2021 09:37:41 AM UTC Stopped all remaining containers ...
	Thu 18 Mar 2021 09:37:42 AM UTC Enabling Watchdog before warm-reboot
	Error: Read failed
	Traceback (most recent call last):
	  File "/usr/local/bin/watchdogutil", line 8, in <module>
		sys.exit(watchdogutil())
	  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
		return self.main(*args, **kwargs)
	  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
		rv = self.invoke(ctx)
	  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1[ 2292.423986] kexec_core: Starting new kernel
	134, in invoke
	[    0.331470] Base address is zero, assuming no IPMI interface
	[    0.435324] Kernel panic - not syncing: Timeout: Not all CPUs entered broadcast exception handler
	[    0.435324] Shutting down cpus with NMI
	[    0.435324] Rebooting in 30 seconds..  <<<<<<<< device hangs here

#### Steps to reproduce the issue:
1. execute fastboot and warmboot and check 

#### Output of `show version`:

	root@sonic-10429:~#
	root@sonic-10429:~# show ver

	SONiC Software Version: SONiC.master.601-be3d4e9a
	Distribution: Debian 10.8
	Kernel: 4.19.0-12-2-amd64
	Build commit: be3d4e9a
	Build date: Thu Mar  4 12:05:25 UTC 2021
	Built by: johnar@jenkins-worker-4

	Platform: x86_64-dellemc_z9332f_d1508-r0
	HwSKU: DellEMC-Z9332f-M-O16C64
	ASIC: broadcom
	ASIC Count: 1

	root@sonic-10429:/#
	root@sonic-10429:/# dpkg -l | grep sai
	ii  libsaibcm                  4.3.3.1                     amd64        Switch Abstraction Interface sdk based on Broadcom SAI
	ii  libsaimetadata             1.0.0                       amd64        This package contains SAI-Metadata implementation for SONiC project.
	ii  libsairedis                1.0.0                       amd64        This package contains SAI-Redis implementation for SONiC project.
	root@sonic-10429:/#

#### Additional information you deem important (e.g. issue happens only occasionally):

show tech support: 
  
[sonic_dump_sonic-10429_20210318_095335.tar.gz](https://github.com/Azure/sonic-buildimage/files/6163196/sonic_dump_sonic-10429_20210318_095335.tar.gz)

**Comment by anshuv-mfst** [comment] 2021-03-31 16:08
@gen-hwa could you please link the master branch issue.

**Comment by gechiang** [comment] 2021-03-31 16:37
There is already an issue filed for this which we found it to be a BRCM SAI issue taht caused warm reboot pre-shutdown failure:
https://github.com/Azure/sonic-buildimage/issues/7071

**Comment by anshuv-mfst** [comment] 2021-03-31 17:30
Closing as this is dup issue.

**Closed by anshuv-mfst** 2021-03-31 17:30 UTC
Labels: Duplicate :dancing_women:

**Comment by vaibhavhd** [comment] 2021-03-31 17:46
Moreover, this errors are unrelated to 7071. This may also be a platform issue:

```
Error: Read failed
Traceback (most recent call last):
  File "/usr/local/bin/watchdogutil", line 8, in <module>
	sys.exit(watchdogutil())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
	return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
	rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1[ 2292.423986] kexec_core: Starting new kernel
134, in invoke
[    0.331470] Base address is zero, assuming no IPMI interface
[    0.435324] Kernel panic - not syncing: Timeout: Not all CPUs entered broadcast exception handler
```

**Comment by gechiang** [comment] 2021-04-06 17:40
@chitra-raghavan The root cause to issue (https://github.com/Azure/sonic-buildimage/issues/7071) has been addressed by latest BRCM SAI in the latest master image.  Can you please try it out and see if you still observe this issue and if so, please reopen this issue so we can investigate it.
You can tell which BRCM SAI your image is using by issuing the following cmd:
```
admin@SONiC:~$ bcmcmd bsv
bsv
BRCM SAI ver: [4.3.3.4], OCP SAI ver: [1.7.1], SDK ver: [sdk-6.5.21]
drivshell>
admin@SONiC:~$
```

If you do not see [4.3.3.4] then you are not running with the latest BRCM SAI.

Thanks!
