### ISSUE TITLE
[201811] [201911] Build failing due to pip setuptools version upgrade

### ISSUE THREAD

**Issue by zhenggen-xu** [Azure/sonic-buildimage#5279] opened 2020-08-31 17:45 UTC
**Description**

Build for 201811 and 201911 fails while building target/docker-snmp-sv2.gz
This is due to issue: https://github.com/pypa/setuptools/issues/2352 

**Steps to reproduce the issue:**
Build 201811 or 201911, you will hit below error:
```
Step 19/28 : RUN python3.6 -m sonic_ax_impl install
 ---> Running in c256862c76fa
[91mTraceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/sonic_ax_impl/__main__.py", line 7, in <module>
    import swsssdk.util
  File "/usr/local/lib/python3.6/dist-packages/swsssdk/__init__.py", line 11, in <module>
    from .dbconnector import SonicDBConfig, SonicV2Connector
  File "/usr/local/lib/python3.6/dist-packages/swsssdk/dbconnector.py", line 5, in <module>
    from .interface import DBInterface
  File "/usr/local/lib/python3.6/dist-packages/swsssdk/interface.py", line 4, in <module>
    import redis
  File "/usr/local/lib/python3.6/dist-packages/redis/__init__.py", line 1, in <module>
    from redis.client import Redis, StrictRedis
  File "/usr/local/lib/python3.6/dist-packages/redis/client.py", line 13, in <module>
    from redis.connection import (ConnectionPool, UnixDomainSocketConnection,
  File "/usr/local/lib/python3.6/dist-packages/redis/connection.py", line 2, in <module>
    from distutils.version import StrictVersion
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "/usr/local/lib/python3.6/dist-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 973, in _gcd_import
  File "<frozen importlib._bootstrap>", line 923, in _sanity_check
SystemError: Parent module 'setuptools' not loaded, cannot perform relative import
[0mThe command '/bin/sh -c python3.6 -m sonic_ax_impl install' returned a non-zero code: 1
[  FAIL LOG END  ] [ target/docker-snmp-sv2.gz ]
slave.mk:541: recipe for target 'target/docker-snmp-sv2.gz' failed
```

**Describe the results you received:**
See above.

**Describe the results you expected:**
Build succesfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by qiluo-msft** [comment] 2020-09-01 21:45
Seems the issue is fixed by upstream https://github.com/pypa/setuptools/issues/2352

**Comment by zhenggen-xu** [comment] 2020-09-01 22:00
it looks like not in 50.0.1, but probably a later release which is not available yet.  We could wait if you guys prefer, but I feel we should make a more deterministic build ourselves, depending on upstream dynamics for our build in general is not a good idea.

**Comment by jleveque** [comment] 2020-09-01 22:13
I'm OK with keeping this change in order to make a more deterministic build. We have been locking down more and more package versions for this reason. Package updates will no longer be unexpected; we will have more control over when we upgrade the packages.

**Closed** 2020-09-02 15:21 UTC
