### ISSUE TITLE
[DPB] After a few consecutive breakout\unbreakout of the interface, the feature stop working

### ISSUE THREAD

**Issue by Hedgehog-Guru** [Azure/sonic-buildimage#6610] opened 2021-01-29 16:23 UTC
**Description**
After a few consecutive breakout\unbreakout of the interface, the feature stop working.

**Steps to reproduce the issue**
1) Breakout interface to 2x50G mode:
```
config interface breakout Ethernet32 2x50G
```
2) Breakout interface back to 1x100G:
```
config interface breakout Ethernet32 1x100G
```
3) One more time try to breakout the same interface to 2x50G mode:
```
config interface breakout Ethernet32 2x50G
```

**Describe the results you received**
Breakout stop working and we get error message:
```
config interface breakout Ethernet32 2x50G 
Do you want to Breakout the port, continue? [y/N]: y

Running Breakout Mode : 1x100G 
Target Breakout Mode : 2x50G

Ports to be deleted : 
 {
    "Ethernet32": "100000"
}
Ports to be added : 
 {
    "Ethernet32": "50000",
    "Ethernet34": "50000"
}

After running Logic to limit the impact

Final list of ports to be deleted : 
 {
    "Ethernet32": "100000"
} 
Final list of ports to be added :  
 {
    "Ethernet32": "50000",
    "Ethernet34": "50000"
}
Loaded below Yang Models
['sonic-acl', 'sonic-breakout_cfg', 'sonic-crm', 'sonic-device_metadata', 'sonic-device_neighbor', 'sonic-extension', 'sonic-flex_counter', 'sonic-interface', 'sonic-loopback-interface', 'sonic-port', 'sonic-portchannel', 'sonic-types', 'sonic-versions', 'sonic-vlan']
Note: Below table(s) have no YANG models:
FEATURE, SNMP_COMMUNITY, SNMP, TELEMETRY, KDUMP, 
libyang[0]: Value "1x100G" does not satisfy the constraint "1x100G\[40G\]|2x50G|4x25G\[10G\]|2x25G\(2\)\+1x50G\(2\)|1x50G\(2\)\+2x25G\(2\)|1x400G|2x200G|4x100G|8x50G|1x200G\[100G,50G,40G,25G,10G,1G\]|2x100G\[50G,40G,25G,10G,1G\]|4x50G\[40G,25G,10G,1G\]|1x25G\[10G\]|1x100G\[50G,40G,25G,10G\]|2x50G\[40G,25G,10G\]|4x25G\[10G\]|1x25G\[10G,1G\]|1x100G\[50G,40G,25G,10G,1G\]|2x50G\[40G,25G,10G,1G\]|4x25G\[10G,1G\]|1x400G\[200G,100G,50G,40G,25G,10G,1G\]|2x200G\[100G,50G,40G,25G,10G,1G\]|4x100G\[50G,40G,25G,10G,1G\]" (range, length, or pattern). (path: /sonic-breakout_cfg:sonic-breakout_cfg/BREAKOUT_CFG/BREAKOUT_CFG_LIST[port='Ethernet32']/brkout_mode)
Data Loading Failed
Failed to break out Port. Error: Failed to load the config. Error: ConfigMgmtDPB Class creation failed
```

**Describe the results you expected**
The feature DPB should continue working after a few consecutive breakout/unbreakout actions.

**Output of show version**
```
SONiC Software Version: SONiC.dpb_qa_image.0-23134a64
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: 23134a64
Build date: Fri Jan 15 08:52:11 UTC 2021
Built by: vadymh@r-build-sonic03

Platform: x86_64-mlnx_msn3800-r0
HwSKU: ACS-MSN3800
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1937X00565
Uptime: 16:19:03 up  1:22,  2 users,  load average: 2.72, 1.32, 1.21

Docker images:
REPOSITORY                    TAG                       IMAGE ID            SIZE
docker-syncd-mlnx             dpb_qa_image.0-23134a64   72cd4f0bad6c        540MB
docker-syncd-mlnx             latest                    72cd4f0bad6c        540MB
docker-sflow                  dpb_qa_image.0-23134a64   070e94ad45b1        465MB
docker-sflow                  latest                    070e94ad45b1        465MB
docker-snmp                   dpb_qa_image.0-23134a64   4513d9bbede9        436MB
docker-snmp                   latest                    4513d9bbede9        436MB
docker-dhcp-relay             dpb_qa_image.0-23134a64   e9f74defdbed        402MB
docker-dhcp-relay             latest                    e9f74defdbed        402MB
docker-teamd                  dpb_qa_image.0-23134a64   4432208a6469        463MB
docker-teamd                  latest                    4432208a6469        463MB
docker-nat                    dpb_qa_image.0-23134a64   b0f25765961f        466MB
docker-nat                    latest                    b0f25765961f        466MB
docker-router-advertiser      dpb_qa_image.0-23134a64   875949f0ef94        395MB
docker-router-advertiser      latest                    875949f0ef94        395MB
docker-platform-monitor       dpb_qa_image.0-23134a64   77567d9ce67c        683MB
docker-platform-monitor       latest                    77567d9ce67c        683MB
docker-lldp                   dpb_qa_image.0-23134a64   9bba135a3864        435MB
docker-lldp                   latest                    9bba135a3864        435MB
docker-database               dpb_qa_image.0-23134a64   ae8be589a33c        394MB
docker-database               latest                    ae8be589a33c        394MB
docker-sonic-mgmt-framework   dpb_qa_image.0-23134a64   9f7fe89d1421        608MB
docker-sonic-mgmt-framework   latest                    9f7fe89d1421        608MB
docker-orchagent              dpb_qa_image.0-23134a64   5928b24d51e3        481MB
docker-orchagent              latest                    5928b24d51e3        481MB
docker-macsec                 dpb_qa_image.0-23134a64   b255f6b0ccf1        466MB
docker-macsec                 latest                    b255f6b0ccf1        466MB
docker-sonic-telemetry        dpb_qa_image.0-23134a64   4e502f1867fd        469MB
docker-sonic-telemetry        latest                    4e502f1867fd        469MB
docker-fpm-frr                dpb_qa_image.0-23134a64   684115a1f6cc        480MB
docker-fpm-frr                latest                    684115a1f6cc        480MB
```
[sonic_dump_r-qa-sw-eth-2322_20210129_161959.tar.gz](https://github.com/Azure/sonic-buildimage/files/5894919/sonic_dump_r-qa-sw-eth-2322_20210129_161959.tar.gz)

**Comment by vadymhlushko-mlnx** [comment] 2021-02-03 17:59
Looks like the duplicate of [Failed to unbreak out a port #6486](https://github.com/Azure/sonic-buildimage/issues/6486)

**Comment by zhenggen-xu** [comment] 2021-02-24 17:41
see: https://github.com/Azure/sonic-utilities/pull/1440

**Comment by zhenggen-xu** [comment] 2021-03-03 04:19
close it since code is merged. Re-open if you see any more issue.

**Closed by zhenggen-xu** 2021-03-03 04:19 UTC
Labels: Port Breakout :trident:
