### ISSUE TITLE
[Dell-Debian9]:  Dell Platform Management Controller module not loaded

### ISSUE THREAD

**Issue by chitra-raghavan** [Azure/sonic-buildimage#2006] opened 2018-08-31 09:46 UTC
**Description**

 Platform Management Controller module not loaded in Dell hardware inDebian9

**Steps to reproduce the issue:**
1. show environment

**Describe the results you received:**

```
root@sonic-s6100-01:~# show environment
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +21.0 C  (high = +98.0 C, crit = +98.0 C)
Core 1:       +21.0 C  (high = +98.0 C, crit = +98.0 C)
Core 2:       +21.0 C  (high = +98.0 C, crit = +98.0 C)
Core 3:       +22.0 C  (high = +98.0 C, crit = +98.0 C)

ERROR:root:S6100 Platform Management Controller module not loaded !

Onboard Temperature Sensors:
  CPU:                             /sys/devices/platform/SMF.512/hwmon/hwmon1/temp1_input not found !
Traceback (most recent call last):
  File "/usr/local/bin/platform_sensors.py", line 100, in <module>
    print_temperature_sensors()
  File "/usr/local/bin/platform_sensors.py", line 58, in print_temperature_sensors
    int(get_pmc_register('temp1_input'))/1000, 'C'
ValueError: invalid literal for int() with base 10: 'ERR'

root@sonic-s6100-01:~# lsmod | grep dell
root@sonic-s6100-01:~#

```

  **Output of `show version`:**

root@sonic-s6100-01:~# show ver
SONiC Software Version: SONiC.master.0-dirty-20180830.090951
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: 3f37b96
Build date: Thu Aug 30 09:13:57 UTC 2018
Built by: lonelyfire@ubuntu

Docker images:
REPOSITORY                 TAG                              IMAGE ID            SIZE
docker-fpm-quagga          latest                           6ad833ee54dd        264.1 MB
docker-fpm-quagga          master.0-dirty-20180830.090951   6ad833ee54dd        264.1 MB
docker-lldp-sv2            latest                           c03d0fc2d426        270.8 MB
docker-lldp-sv2            master.0-dirty-20180830.090951   c03d0fc2d426        270.8 MB
docker-snmp-sv2            latest                           7b463619af86        291.2 MB
docker-snmp-sv2            master.0-dirty-20180830.090951   7b463619af86        291.2 MB
docker-orchagent-brcm      latest                           25f2951795a8        257.6 MB
docker-orchagent-brcm      master.0-dirty-20180830.090951   25f2951795a8        257.6 MB
docker-platform-monitor    latest                           6416fe799722        283.3 MB
docker-platform-monitor    master.0-dirty-20180830.090951   6416fe799722        283.3 MB
docker-teamd               latest                           cb3ea79e20cf        257.3 MB
docker-teamd               master.0-dirty-20180830.090951   cb3ea79e20cf        257.3 MB
docker-syncd-brcm          latest                           fa4ccc644bcf        336.4 MB
docker-syncd-brcm          master.0-dirty-20180830.090951   fa4ccc644bcf        336.4 MB
docker-database            latest                           eac364fc5f11        252.3 MB
docker-database            master.0-dirty-20180830.090951   eac364fc5f11        252.3 MB
docker-dhcp-relay          latest                           ab2d6bb2f6bc        253.7 MB
docker-dhcp-relay          master.0-dirty-20180830.090951   ab2d6bb2f6bc        253.7 MB
docker-router-advertiser   latest                           1c9d6dd0feb8        250 MB
docker-router-advertiser   master.0-dirty-20180830.090951   1c9d6dd0feb8        250 MB

**Comment by xinliu-seattle** [comment] 2018-09-02 00:58
I am contacting Dell to take a look at this issue.

**Comment by lguohan** [comment] 2018-09-11 04:27
addressed in #2026

**Comment by lguohan** [comment] 2018-09-12 16:45
@chitra-raghavan , can you confirm if the issue is addressed or not.

**Comment by chitra-raghavan** [comment] 2018-09-13 05:38
The platform modules doesnt get loaded  when the image is loaded for first time. It gets loaded only after reboot.

```
root@sonic:~# show environment
coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +21.0 C  (high = +98.0 C, crit = +98.0 C)
Core 1:       +21.0 C  (high = +98.0 C, crit = +98.0 C)
Core 2:       +25.0 C  (high = +98.0 C, crit = +98.0 C)
Core 3:       +24.0 C  (high = +98.0 C, crit = +98.0 C)

ERROR:root:S6100 Platform Management Controller module not loaded !
Traceback (most recent call last):
  File "/usr/local/bin/platform_sensors.py", line 100, in <module>
    print_temperature_sensors()
  File "/usr/local/bin/platform_sensors.py", line 58, in print_temperature_sensors
    int(get_pmc_register('temp1_input'))/1000, 'C'
ValueError
: invalid literal for int() with base 10: 'ERR'
Onboard Temperature Sensors:
  CPU:                             /sys/devices/platform/SMF.512/hwmon/hwmon1/temp1_input not found !
root@sonic:~#
root@sonic:~# show ver
SONiC Software Version: SONiC.HEAD.709-5d23a43
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: 5d23a43
Build date: Wed Sep 12 14:11:17 UTC 2018
Built by: johnar@jenkins-worker-3

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-syncd-brcm          HEAD.709-5d23a43    b49d02995620        336.8 MB
docker-syncd-brcm          latest              b49d02995620        336.8 MB
docker-orchagent-brcm      HEAD.709-5d23a43    80a6e8dbcfc5        258.1 MB
docker-orchagent-brcm      latest              80a6e8dbcfc5        258.1 MB
docker-lldp-sv2            HEAD.709-5d23a43    f57ccc6afe6d        271.4 MB
docker-lldp-sv2            latest              f57ccc6afe6d        271.4 MB
docker-dhcp-relay          HEAD.709-5d23a43    18accd42e7fb        254 MB
docker-dhcp-relay          latest              18accd42e7fb        254 MB
docker-database            HEAD.709-5d23a43    3fae32211ef2        252.7 MB
docker-database            latest              3fae32211ef2        252.7 MB
docker-teamd               HEAD.709-5d23a43    103d6a5bb6b4        257.8 MB
docker-teamd               latest              103d6a5bb6b4        257.8 MB
docker-snmp-sv2            HEAD.709-5d23a43    4e55eb4c2dd2        291.2 MB
docker-snmp-sv2            latest              4e55eb4c2dd2        291.2 MB
docker-router-advertiser   HEAD.709-5d23a43    8509c84a90c0        250 MB
docker-router-advertiser   latest              8509c84a90c0        250 MB
docker-platform-monitor    HEAD.709-5d23a43    3b39477b5703        283.5 MB
docker-platform-monitor    latest              3b39477b5703        283.5 MB
docker-fpm-quagga          HEAD.709-5d23a43    b682c6b001c3        264.3 MB
docker-fpm-quagga          latest              b682c6b001c3        264.3 MB

root@sonic:~# lsmod | grep dell
root@sonic:~#
root@sonic:~# reboot
Stopping syncd...
requested COLD shutdown
[  OK  ] Stopped LLDP container.
[  OK  ] Stopped Update minigraph and set configuration based on minigraph.
...
...
...
root@sonic:~#
root@sonic:~# lsmod | grep dell
dell_s6100_lpc         53248  0
dell_s6100_iom_cpld    16384  0
dell_ich               20480  0
root@sonic:~#
root@sonic:~#
root@sonic:~#
```

**Closed** 2018-10-05 21:31 UTC
Labels: platform-dell
