### ISSUE TITLE
[chassis][multi-asic] Load minigraph is failing on multi asic linecards

### ISSUE THREAD

**Issue by arlakshm** [Azure/sonic-buildimage#11271] opened 2022-06-28 06:52 UTC
#### Description
The CLI command `config load_minigraph` is failing on multi asic linecards with the following error

```
admin@sonic:~$ sudo config load_minigraph -y
Disabling container monitoring ...
Stopping SONiC target ...
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json   --write-to-db
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json  -n asic0 --write-to-db
/usr/local/lib/python3.9/dist-packages/minigraph.py:485: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if voqinbandintfs:
Running command: /usr/local/bin/sonic-cfggen -H -m -j /etc/sonic/init_cfg.json  -n asic1 --write-to-db
/usr/local/lib/python3.9/dist-packages/minigraph.py:485: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if voqinbandintfs:
Warning: mirror table EVERFLOW in ACL_TABLE does not have any ports bound to it
Warning: mirror table EVERFLOWV6 in ACL_TABLE does not have any ports bound to it
Running command: /usr/local/bin/sonic-cfggen -d -y /etc/sonic/sonic_version.yml -t /usr/share/sonic/templates/sonic-environment.j2,/etc/sonic/sonic-environment
Running command: config qos reload --no-dynamic-buffer
<snip>
...
Running command: pfcwd start_default
Traceback (most recent call last):
  File "/usr/local/bin/pfcwd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 57, in new_func
    obj = ctx.ensure_object(object_type)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 477, in ensure_object
    self.obj = rv = object_type()
  File "/usr/local/lib/python3.9/dist-packages/utilities_common/db.py", line 36, in __init__
    multi_asic.connect_config_db_for_ns(ns)
  File "/usr/local/lib/python3.9/dist-packages/sonic_py_common/multi_asic.py", line 43, in connect_config_db_for_ns
    config_db = swsscommon.ConfigDBConnector(namespace=namespace)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1945, in __init__
    super(ConfigDBConnector, self).__init__(use_unix_socket_path = use_unix_socket_path, namespace = namespace)
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1575, in __init__
    for db_name in self.get_db_list():
  File "/usr/lib/python3/dist-packages/swsscommon/swsscommon.py", line 1511, in get_db_list
    return _swsscommon.SonicV2Connector_Native_get_db_list(self)
RuntimeError: :- validateNamespace: Initialize global DB config using API SonicDBConfig::initializeGlobalConfig
```

#### Steps to reproduce the issue:
1. Execute the command `config load_minigraph` on the latest master image
2.
3.

#### Describe the results you received:
The command fails. 

#### Output of `show version`:

```
Error: No such command "vwrs".
admin@sonic:~$ show vers

SONiC Software Version: SONiC.master.114766-9d5ca72b8
Distribution: Debian 11.3
Kernel: 5.10.0-12-2-amd64
Build commit: 9d5ca72b8
Build date: Sun Jun 26 15:39:21 UTC 2022
Built by: AzDevOps@sonic-build-workers-001OOY
```
#### Output of `show techsupport`:

```
(paste your output here or download and attach the file here )
```

**Comment by SuvarnaMeenakshi** [comment] 2022-06-29 00:34
duplicate of https://github.com/Azure/sonic-buildimage/issues/11269

**Comment by rlhui** [comment] 2022-07-12 09:37
@SuvarnaMeenakshi - if this is fixed, please close it. thanks.

**Comment by SuvarnaMeenakshi** [comment] 2022-07-12 16:38
https://github.com/Azure/sonic-buildimage/issues/11269 is closed and fix is merged.

**Closed by SuvarnaMeenakshi** 2022-07-12 16:38 UTC
Labels: Chassis :robot:
