### ISSUE TITLE
[DHCPv6] dhcpv6 packets doesn't forwarded

### ISSUE THREAD

**Issue by AntonHryshchuk** [Azure/sonic-buildimage#10785] opened 2022-05-09 11:06 UTC
#### Description

dhcpv6 packets doesn't forwarded

The suspicious changes:

https://github.com/Azure/sonic-buildimage/pull/10486
https://github.com/Azure/sonic-buildimage/pull/10712

#### Steps to reproduce the issue:
Reproduced on simple setup which contains the 2 Hosts and 1 Switch. The Hosts are connected by one cable directly to the switch and don't connect between themselves.
HostA <-> Switch <-> HostB

**The connectivity in the provided example:**
HostA::enp4s0f0 <-> Switch::Ethernet64
HostB::enp6s0f0<-> Switch::Ethernet0

**HostA configurations:**
```
sudo ip link add link enp4s0f0 name enp4s0f0.690 type vlan id 690
sudo ip link set enp4s0f0.690 up
echo "timeout 10;" > dhclient.conf
```

**HostB configurations:**
Update the file /etc/dhcp/dhcpd6.conf:
```
default-lease-time 600;
max-lease-time 7200;
log-facility local7;

# VLAN 69
subnet6 6900::/64 {
range6 6900::129 6900::254;
}
# VLAN 690
subnet6 6900:1::/64 {
range6 6900:1::129 6900:1::254;
}
```

2. Cli configurations:
```
sudo ip link add bond0 type bond
sudo ip link set dev bond0 type bond mode 4
sudo ip link set enp6s0f0 down
sudo ip link set enp6s0f0 master bond0
sudo ip link set enp6s0f0 up
sudo ip link set bond0 up
sudo ip link add link bond0 name bond0.69 type vlan id 69
sudo ip link set bond0.69 up
sudo ip addr add 6900::2/64 dev bond0.69
sudo ip route add 6900:1::/64 via 6900::1
sed -e "s/INTERFACESv6=\"\"/INTERFACESv6=\"bond0.69\"/g" -i /etc/default/isc-dhcp-server
/etc/init.d/isc-dhcp-server restart
```

**Switch configurations:**
```
sudo config portchannel add PortChannel0002
sudo config portchannel member add PortChannel0002 Ethernet0

sudo config vlan add 69
sudo config vlan member add 69 PortChannel0002
sudo config vlan add 690
sudo config vlan member add 690 Ethernet64

sudo config interface ip add Vlan690 6900:1::1/64
sudo config interface ip add Vlan69 6900::1/64

sudo sonic-db-cli CONFIG_DB HSET "DHCP_RELAY|Vlan690" "dhcpv6_servers@" "6900::2"
sudo sonic-db-cli CONFIG_DB HSET "VLAN|Vlan690" "dhcpv6_servers@" "6900::2"
sudo service dhcp_relay restart

# validate the server
show dhcprelay_helper ipv6
```

#### Describe the results you received:
On the switch, the requests from the Client are not forwarded to the PortChannel member.
No answer to the request from the client (HostA):
```
hostA:~#timeout 10 dhclient -6 enp4s0f0.690 -v

Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on Socket/enp4s0f0.690
Sending on   Socket/enp4s0f0.690
PRC: Soliciting for leases (INIT).
XMT: Forming Solicit, 0 ms elapsed.
XMT:  X-- IA_NA a1:17:e6:fc
XMT:  | X-- Request renew in  +3600
XMT:  | X-- Request rebind in +5400
XMT: Solicit on enp4s0f0.690, interval 1020ms.
XMT: Forming Solicit, 1020 ms elapsed.
XMT:  X-- IA_NA a1:17:e6:fc
XMT:  | X-- Request renew in  +3600
XMT:  | X-- Request rebind in +5400
XMT: Solicit on enp4s0f0.690, interval 1980ms.
XMT: Forming Solicit, 3000 ms elapsed.
XMT:  X-- IA_NA a1:17:e6:fc
XMT:  | X-- Request renew in  +3600
XMT:  | X-- Request rebind in +5400
XMT: Solicit on enp4s0f0.690, interval 4090ms.
XMT: Forming Solicit, 7090 ms elapsed.
XMT:  X-- IA_NA a1:17:e6:fc
XMT:  | X-- Request renew in  +3600
XMT:  | X-- Request rebind in +5400
XMT: Solicit on enp4s0f0.690, interval 7840ms.
```

#### Describe the results you expected:
The Client got a reply: 
```
hostA~# timeout 10 dhclient -6 enp4s0f0.690 -v
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on Socket/enp4s0f0.690
Sending on   Socket/enp4s0f0.690
PRC: Confirming active lease (INIT-REBOOT).
XMT: Forming Confirm, 0 ms elapsed.
XMT:  X-- IA_NA 9b:97:3a:ce
XMT:  | X-- Confirm Address 6900:1::254
XMT:  V IA_NA appended.
XMT: Confirm on enp4s0f0.690, interval 960ms.
RCV: Reply message on enp4s0f0.690 from fe80::ba59:9fff:fea9:3400.
RCV:  X-- Server ID: 00:01:00:01:2a:0b:23:a2:0c:42:a1:46:55:8a
message status code Success: "All addresses still on link."
PRC: Bound to lease 00:01:00:01:2a:0b:23:a2:0c:42:a1:46:55:8a.
```

tcpdump on the portchannel member:
```
10:09:56.069132 IP6 6900:1::1.dhcpv6-server > 6900::2.dhcpv6-server: dhcp6 relay-fwd
10:09:56.069673 IP6 6900::2.dhcpv6-server > 6900:1::1.dhcpv6-server: dhcp6 relay-reply
10:09:57.730597 IP6 6900:1::1.dhcpv6-server > 6900::2.dhcpv6-server: dhcp6 relay-fwd
10:09:57.731189 IP6 6900::2.dhcpv6-server > 6900:1::1.dhcpv6-server: dhcp6 relay-reply
```
#### Output of `show version`:

```
root@r-51:/home/admin# show version 

SONiC Software Version: SONiC.202111.66-375e20338_Internal
Distribution: Debian 11.3
Kernel: 5.10.0-8-2-amd64
Build commit: 375e20338
Build date: Sun May  8 13:46:29 UTC 2022
Built by: sw-r2d2-bot@r-build-sonic-ci02-242

Platform: x86_64-mlnx_msn3700-r0
HwSKU: ACS-MSN3700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT1949X06182
Model Number: MSN3700-VS2F
Hardware Revision: A3
Uptime: 11:04:26 up  1:54,  1 user,  load average: 0.43, 0.64, 0.61
```

**Comment by kellyyeh** [comment] 2022-05-10 16:49
Thanks @AntonHryshchuk, could you confirm if Relay-Forward packets are generated? Would be great if you can attached a tcpdump/pcap of the client packets

**Comment by kellyyeh** [comment] 2022-05-11 19:50
@AntonHryshchuk I confirmed the latest dhcp6relay to have no issue relaying packets. Can you confirm if relay-forward is generated? And a tcpdump/pcap of the client packets would be great.

**Comment by AntonHryshchuk** [comment] 2022-05-12 06:29
>@AntonHryshchuk I confirmed the latest dhcp6relay to have no issue relaying packets. Can you confirm if relay-forward is generated? And a tcpdump/pcap of the client packets would be great.

**The tcpdump on previous version, which works:**

tcpdump on the interface to the server(interface member in LAG):
```
root@r-51:/home/admin# tcpdump -i Ethernet60
05:51:11.151473 IP6 fe80::1e34:daff:fe16:6800 > ff02::1:ff00:2: ICMP6, neighbor solicitation, who has 6900::2, length 32
05:51:11.151621 IP6 6900::2 > fe80::1e34:daff:fe16:6800: ICMP6, neighbor advertisement, tgt is 6900::2, length 32
05:51:11.151727 IP6 6900:1::1.dhcpv6-server > 6900::2.dhcpv6-server: dhcp6 relay-fwd
05:51:11.152242 IP6 fe80::e42:a1ff:fe4b:b6d > ff02::1:ff00:1: ICMP6, neighbor solicitation, who has 6900::1, length 32
05:51:11.152356 IP6 6900::1 > fe80::e42:a1ff:fe4b:b6d: ICMP6, neighbor advertisement, tgt is 6900::1, length 32
05:51:11.152268 IP6 6900::2 > ff02::1:ff00:1: ICMP6, neighbor solicitation, who has 6900::1, length 32
05:51:11.152422 IP6 6900::1 > 6900::2: ICMP6, neighbor advertisement, tgt is 6900::1, length 32
05:51:11.152476 IP6 6900::2.dhcpv6-server > 6900:1::1.dhcpv6-server: dhcp6 relay-reply
05:51:11.202491 IP randomtest-ch01.am.lilly.com.bgp > 40.0.0.3.46852: Flags [P.], seq 20:141, ack 19, win 494, options [nop,nop,TS val 4069217049 ecr 3065886138], length 121: BGP
05:51:11.202604 IP 40.0.0.3.46852 > randomtest-ch01.am.lilly.com.bgp: Flags [.], ack 141, win 501, options [nop,nop,TS val 3065908740 ecr 4069217049], length 0
05:51:12.242814 IP6 6900:1::1.dhcpv6-server > 6900::2.dhcpv6-server: dhcp6 relay-fwd
05:51:12.243199 IP6 6900::2.dhcpv6-server > 6900:1::1.dhcpv6-server: dhcp6 relay-reply
```

tcpdump on interface to Client:
```
root@r-51:/home/admin# tcpdump -i Ethernet124
05:51:11.151026 IP6 fe80::e42:a1ff:fe17:e6fd.dhcpv6-client > ff02::1:2.dhcpv6-server: dhcp6 solicit
05:51:11.153029 IP6 fe80::1e34:daff:fe16:6800.dhcpv6-server > fe80::e42:a1ff:fe17:e6fd.dhcpv6-client: dhcp6 advertise
05:51:12.242370 IP6 fe80::e42:a1ff:fe17:e6fd.dhcpv6-client > ff02::1:2.dhcpv6-server: dhcp6 request
05:51:12.243522 IP6 fe80::1e34:daff:fe16:6800.dhcpv6-server > fe80::e42:a1ff:fe17:e6fd.dhcpv6-client: dhcp6 reply
05:51:12.443773 IP6 :: > ff02::1:ff00:254: ICMP6, neighbor solicitation, who has 6900:1::254, length 32
05:51:16.187039 IP6 fe80::1e34:daff:fe16:6800 > fe80::e42:a1ff:fe17:e6fd: ICMP6, neighbor solicitation, who has fe80::e42:a1ff:fe17:e6fd, length 32
05:51:16.187175 IP6 fe80::e42:a1ff:fe17:e6fd > fe80::1e34:daff:fe16:6800: ICMP6, neighbor advertisement, tgt is fe80::e42:a1ff:fe17:e6fd, length 24
```




**The tcpdump on the version, which contains the issue:**
tcpdump on the interface to Server(interface member in LAG):
```
root@r-51:/home/admin# tcpdump -i Ethernet60
06:16:55.843543 LACPv1, length 110
06:16:57.727201 IP 40.0.0.3.47204 > randomtest-ch01.am.lilly.com.bgp: Flags [P.], seq 2206273350:2206273369, ack 302363232, win 501, options [nop,nop,TS val 3067454962 ecr 3454542761], length 19: BGP
06:16:57.727290 IP randomtest-ch01.am.lilly.com.bgp > 40.0.0.3.47204: Flags [.], ack 19, win 494, options [nop,nop,TS val 3454602759 ecr 3067454962], length 0
06:16:57.728942 IP randomtest-ch01.am.lilly.com.bgp > 40.0.0.3.47204: Flags [P.], seq 1:20, ack 19, win 494, options [nop,nop,TS val 3454602761 ecr 3067454962], length 19: BGP
06:16:57.729047 IP 40.0.0.3.47204 > randomtest-ch01.am.lilly.com.bgp: Flags [.], ack 20, win 501, options [nop,nop,TS val 3067454964 ecr 3454602761], length 0
06:17:01.842083 LACPv1, length 110
06:17:03.066038 ARP, Request who-has randomtest-ch01.am.lilly.com tell 40.0.0.3, length 42
06:17:03.066113 ARP, Reply randomtest-ch01.am.lilly.com is-at 1c:34:da:16:68:00 (oui Unknown), length 28
```

tcpdump on the interface to Client:
```
root@r-51:/home/admin# tcpdump -i Ethernet124
06:16:49.702446 IP6 fe80::e42:a1ff:fe17:e6fd.dhcpv6-client > ff02::1:2.dhcpv6-server: dhcp6 solicit
06:16:50.793704 IP6 fe80::e42:a1ff:fe17:e6fd.dhcpv6-client > ff02::1:2.dhcpv6-server: dhcp6 solicit
06:16:52.895971 IP6 fe80::e42:a1ff:fe17:e6fd.dhcpv6-client > ff02::1:2.dhcpv6-server: dhcp6 solicit
06:16:57.110338 IP6 fe80::e42:a1ff:fe17:e6fd.dhcpv6-client > ff02::1:2.dhcpv6-server: dhcp6 solicit
```

**Comment by kellyyeh** [comment] 2022-05-12 09:07
@AntonHryshchuk Can you increase verbosity on client side tcpdump so I can see Solicit options? I suspect https://github.com/Azure/sonic-buildimage/pull/10486 could be the culprit, but I cannot reproduce the issue on my side. Would also appreciate if you could include the counter after sending client requests. Command is `sudo show dhcp6relay_counters counts`

**Comment by shlomibitton** [comment] 2022-05-12 09:15
@kellyyeh it is indeed https://github.com/Azure/sonic-buildimage/pull/10486 causing this degradation.
I verified it by running the test with and without this commit and this is the root cause.

from tcpdump with highest verbosity:

09:14:38.691841 IP6 (flowlabel 0x3459f, hlim 1, next-header UDP (17) payload length: 92) fe80::e42:a1ff:fe17:e6fd.dhcpv6-client > ff02::1:2.dhcpv6-server: [udp sum ok] dhcp6 confirm (xid=4cd220 (client-ID hwaddr/time type 1 time 705627101 0c42a117e6fd) (option-request DNS-server DNS-search-list Client-FQDN SNTP-servers) (elapsed-time 0) (IA_NA IAID:2702698237 T1:0 T2:0 (IA_ADDR 6900:1::254 pltime:0 vltime:0)))

**Comment by kellyyeh** [comment] 2022-05-12 09:30
@shlomibitton  Thanks for the output. Confirm message type was missed, and the issue should be resolved by the PR linked. Will also file a test gap for this

**Comment by shlomibitton** [comment] 2022-05-12 09:47
I tried to add you fix and compile, but it is not fixing the issue, SOLICIT messages also dropped.

![image](https://user-images.githubusercontent.com/60430976/168042928-c932c795-b9ff-4628-9b31-172773f7bf56.png)

**Comment by dprital** [comment] 2022-05-19 11:54
@kellyyeh - What is the ETA for a fix ?

**Comment by kellyyeh** [comment] 2022-05-20 05:29
@dprital Here is the PR fix: https://github.com/Azure/sonic-buildimage/pull/10819 @shlomibitton I tested on my end to be working. Could you verify with the PR build on your end if it fixes your issue?

**Comment by shlomibitton** [comment] 2022-05-23 08:10
@kellyyeh I tested your fix and it is working, thanks!
Once the PR is merged we can close this issue.

**Closed** 2022-05-24 21:37 UTC
Labels: Triaged, MSFT
