### ISSUE TITLE
ntpd uses incorrect src ip for requests via front panel and mgmt ports

### ISSUE THREAD

**Issue by mkovnir** [Azure/sonic-buildimage#5598] opened 2020-10-12 14:10 UTC
**Description**

NTPd uses incorrect src ip for requests toward configured servers. 

**Steps to reproduce the issue:**
1. Configure NTP servers (either via dhcp or static)
2. Configure Loopback0 with IP
3. Reboot
4. Do capture on egress interface. 

**Describe the results you received:**
If system is configured with loopback0 and mgmt interfaces - NTPd uses Loopback0's IP as source for requests via mgmt interface.
If system is configured with mgmt interface - NTPd uses mgmt's IP as source for requests via inband (front panel) ports.

**Describe the results you expected:**
NTPd should use egress interface's IP address:
- if NTP server is reachable over mgmt interface, IP of mgmt interface should be used.
- if NTP server is reachable over front panel port/vlan interface - IP of port/vlan should be used.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `show version`:**

``` SONiC Software Version: SONiC.201911.210-cc135807
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: cc135807
Build date: Wed Oct  7 04:18:37 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-mlnx_msn4600c-r0
HwSKU: ACS-MSN4600C
ASIC: mellanox
Serial Number: MT2023X20779    ```

[sonic_dump_r-qa-sw-eth-20123_20201012_140454.tar.gz](https://github.com/Azure/sonic-buildimage/files/5369380/sonic_dump_r-qa-sw-eth-20123_20201012_140454.tar.gz)

**Comment by anshuv-mfst** [comment] 2020-10-14 15:39
Was the configuration saved before reboot? 
Is the same issue seem when restarting the NTP deamon?

**Comment by mkovnir** [comment] 2020-10-15 14:01
Yes, configuration was saved before reboot.
Yes, same issue when NTP is restarted (via systemctl restart ntp).

**Comment by anshuv-mfst** [comment] 2020-10-28 16:03
@SuvarnaMeenakshi - could you please look into this issue.

**Comment by SuvarnaMeenakshi** [comment] 2020-11-11 16:18
In SONiC, ntp-config service creates /etc/ntp.conf which is the ntp configuration used by ntp service.
/etc/ntp.conf is created from a template ntp.conf.j2. 
This template ensures that only Management IP or Loopback IP is used to listen, if both are configured.
If there is no management IP or Loopback IP, then it listens on all interfaces.
I don't see the issue described in the experiments done on VS DUT.

Scenarios:
1. Only management IP is configured  - management IP is used as source - Looks right
2. Only Loopback IP is configured with NTP server reachable from front panel interface - Loopback IP is used as source - Looks right
3. Both Management and Loopback configured (Scenario should not happen in SONiC configuration)
4. No interface configured and NTP server reachable over front-panel interface 

In both scenario 3 and scenario 4, Management IP is used, though the server is reachable from front panel interface.

Tried all scenarios on VS testbed by modifying /etc/ntp.conf and restarting ntp-config.service (modifed /usr/bin/ntp-config.sh to not create ntp.conf from template)

Scenario 2:
To check the scenario using Loopback IP, used the VS testbed setup.
With this set up, modified ntp.conf to use Loopback IP address.
```
interface ignore wildcard
interface listen 10.1.0.32

Seeing packets going with correct Src IP, which is the Loopback IP: 
admin@vlab-01:~$ sudo tcpdump -i Ethernet112 port 123
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on Ethernet112, link-type EN10MB (Ethernet), capture size 262144 bytes
11:47:06.776547 IP 10.1.0.32.ntp > 10.0.0.57.ntp: NTPv4, Client, length 48
11:48:10.776706 IP 10.1.0.32.ntp > 10.0.0.57.ntp: NTPv4, Client, length 48
11:49:16.776724 IP 10.1.0.32.ntp > 10.0.0.57.ntp: NTPv4, Client, length 48
11:50:23.776527 IP 10.1.0.32.ntp > 10.0.0.57.ntp: NTPv4, Client, length 48
```
Scenario 3:
Both management IP and Loopback IP is configured in /etc/ntp.conf, Server is reachable via front panel port.
Packet has Loopback IP as source IP which looks correct.
```
/etc/ntp.conf
interface ignore wildcard
interface listen 10.1.0.32
interface listen 10.250.0.101

admin@vlab-01:~$ sudo tcpdump -i Ethernet112 port 123
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on Ethernet112, link-type EN10MB (Ethernet), capture size 262144 bytes
12:18:31.525419 IP 10.1.0.32.ntp > 10.0.0.57.ntp: NTPv4, Client, length 48
12:19:35.525365 IP 10.1.0.32.ntp > 10.0.0.57.ntp: NTPv4, Client, length 48
```

On Arista with NTP server:

12:20:40.806025 52:54:00:7d:b6:4f > 02:ea:ef:91:5f:08, ethertype IPv4 (0x0800), length 90: 10.1.0.32.ntp > 10.0.0.57.ntp: NTPv4, Client, length 48
```
Scenario 4: no packet going out
```
/etc/ntp.conf
interface ignore wildcard

admin@vlab-01:~$ netstat -tulnp | grep 123
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
udp        0      0 127.0.0.1:123           0.0.0.0:*                           -                   
udp6       0      0 ::1:123                 :::*    
```

**Comment by liat-grozovik** [comment] 2020-12-29 08:21
@anshuv-mfst  and @SuvarnaMeenakshi the issue is in stage of waiting info. is this still correct?
is there any assignee on this issue so we can follow up?

**Comment by SuvarnaMeenakshi** [comment] 2020-12-31 01:22
@liat-grozovik having tried out couple of cases that I mentioned above, It does not seem to be a valid issue.
@mkovnir can confirm if the explanation is good or if there is still something to be looked at.
If not we can close this issue.

**Comment by Hedgehog-Guru** [comment] 2021-03-17 08:34
Verified under hash 5263478 FROM 202012 branch.
The issue is not reproduced. Considered as fixed by the community.
Thanks.

**Closed** 2021-03-17 08:41 UTC
Labels: Awaiting Info :hourglass:
