### ISSUE TITLE
The switch will be crashed when inputting "reboot" command under host

### ISSUE THREAD

**Issue by kaiyu22** [Azure/sonic-buildimage#389] opened 2017-03-09 01:39 UTC
Hi all,

I found that there is a trace back issue in master (commitment 1491bf9). When user inputting "reboot" command under host, the switch will be crashed.  After investigating, it maybe relates to commitment a877603 (Merge swss and syncd into single service)

The following is the error message.

    [  207.772520] BUG: unable to handle kernel paging request at ffffffffa03ff0f0
    [  207.780338] IP: [<ffffffff811a746f>] filp_close+0x1f/0x70
    [  207.786396] PGD 1816067 PUD 1817063 PMD 27346a067 PTE 0
    [  207.792260] Oops: 0000 [#1] SMP 
    [  207.795872] Modules linked in: eeprom_mb(O) eeprom w83795 jc42 coretemp bridge stp llc i2c_mux_pca954x i2c_mux i2c_dev i2c_ismt i2c_i801 kvm_intel kvm crc32_pclmul xt_conntrack iTCO_wdt iTCO_vendor_support iptable_filter ipt_MASQUERADE aesni_intel aes_x86_64 xt_addrtype lrw gf128mul glue_helper ablk_helper lpc_ich mfd_core evdev cryptd serio_raw pcspkr iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 ipmi_msghandler tpm_tis tpm button nf_nat_ipv4 shpchp i2c_core nf_nat acpi_cpufreq nf_conntrack processor thermal_sys ip_tables x_tables autofs4 loop ext4 crc16 mbcache jbd2 nls_utf8 nls_cp437 vfat fat aufs(C) squashfs sg sd_mod crc_t10dif crct10dif_generic crct10dif_pclmul crct10dif_common crc32c_intel ahci libahci libata ehci_pci ehci_hcd scsi_mod igb(O) usbcore usb_common dca ptp pps_core [last unloaded: linux_kernel_bde]
    [  207.877421] CPU: 1 PID: 1555 Comm: syncd Tainted: G         C O  3.16.0-4-amd64 #1 Debian 3.16.36-1+deb8u2
    [  207.896132] task: ffff880036dbe190 ti: ffff8802731bc000 task.ti: ffff8802731bc000
    [  207.904518] RIP: 0010:[<ffffffff811a746f>]  [<ffffffff811a746f>] filp_close+0x1f/0x70
    [  207.913283] RSP: 0018:ffff8802731bfce0  EFLAGS: 00010246
    [  207.919232] RAX: ffffffffa03ff080 RBX: ffff88027349ff00 RCX: 0000000000000027
    [  207.927227] RDX: ffff880272466858 RSI: ffff880272466800 RDI: ffff88027349ff00
    [  207.935215] RBP: ffff880272466800 R08: ffff8802731bc000 R09: 000000000000b8fe
    [  207.943211] R10: 0000000000000001 R11: 0000000000000000 R12: 0000000000000000
    [  207.951207] R13: ffff880272466800 R14: 0000000000000001 R15: ffff880272466810
    [  207.959205] FS:  00007f4388398740(0000) GS:ffff88027fc80000(0000) knlGS:0000000000000000
    [  207.968274] CS:  0010 DS: 0000 ES: 0000 CR0: 000000008005003b
    [  207.974711] CR2: ffffffffa03ff0f0 CR3: 000000027317b000 CR4: 00000000001007e0
    [  207.982708] Stack:
    [  207.984956]  00000000000002ff 0000000000000027 0000000000000000 ffffffff811c5898
    [  207.993262]  ffff880036dbe810 ffff880272a67400 ffff880272a67460 0000000000000005
    [  208.001566]  ffff880036fe8760 ffff880036dbe190 ffffffff81069c0e ffff8802731bff58
    [  208.009872] Call Trace:
    [  208.012602]  [<ffffffff811c5898>] ? put_files_struct+0x78/0xc0
    [  208.019142]  [<ffffffff81069c0e>] ? do_exit+0x28e/0xa70
    [  208.024997]  [<ffffffff8106a469>] ? do_group_exit+0x39/0xa0
    [  208.031241]  [<ffffffff81078928>] ? get_signal_to_deliver+0x1c8/0x5d0
    [  208.038461]  [<ffffffff81013492>] ? do_signal+0x42/0xa10
    [  208.044412]  [<ffffffff810779c4>] ? do_send_sig_info+0x54/0x70
    [  208.050949]  [<ffffffff81013ed8>] ? do_notify_resume+0x78/0xa0
    [  208.057488]  [<ffffffff81518a8a>] ? int_signal+0x12/0x17
    [  208.063437] Code: 66 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 41 54 55 53 48 8b 47 38 48 89 fb 48 85 c0 74 44 48 8b 47 28 45 31 e4 48 89 f5 <48> 8b 40 70 48 85 c0 74 05 ff d0 41 89 c4 f6 43 45 40 75 16 48 
    [  208.084896] RIP  [<ffffffff811a746f>] filp_close+0x1f/0x70
    [  208.091039]  RSP <ffff8802731bfce0>
    [  208.094942] CR2: ffffffffa03ff0f0
    [  208.098652] ---[ end trace 7dcc5bf3c94d2437 ]---

Does anyone encounter this issue?

**Comment by stcheng** [comment] 2017-03-09 08:41
thanks for submitting the issue. we will try to reproduce this.

**Comment by lguohan** [comment] 2017-03-18 01:25
ack, I am seeing such issue. will investigate

**Comment by jleveque** [comment] 2017-03-21 23:53
I am seeing this quite consistently.

**Comment by stcheng** [comment] 2017-03-22 04:47
@marian-pritsak Do you see this error?

**Comment by stcheng** [comment] 2017-03-22 23:40
https://github.com/Azure/sonic-buildimage/issues/425 related?

**Comment by pavel-shirshov** [comment] 2017-03-22 23:44
I don't think so. I think it's related to brcm platform only and it requires reboot by power.

**Comment by jleveque** [comment] 2017-03-23 01:05
@stcheng: I was also wondering if they might be related.

@pavel-shirshov: What do you mean "reboot by power?" Are you saying the switch locks up and requires a power cycle? If so, which bug are you referring to? I can safely state that I see both of these problems on my dev switch upon reboot, and the machine will eventually reboot, not requiring a power cycle. A couple weeks ago I found myself needing to power cycle the switch occasionally after reboot, but that seems to have subsided.

**Comment by pavel-shirshov** [comment] 2017-03-23 18:07
Joe,
Yes, the switch locks up, it doesn't responds on its console and I need to use a power reset to return it from this state. I'm referring to this https://github.com/Azure/sonic-buildimage/issues/389#issuecomment-288255933 stack trace. When I get such stack trace my development switch locks up.

**Comment by stcheng** [comment] 2017-03-24 01:32
Need to debug the syncd docker. It seems to be some driver related stuffs.
I remove the syncd docker manually before reboot and no such issues found.

**Comment by jleveque** [comment] 2017-03-27 21:28
@kaiyu22: It seems as though we have fixed this with PR #434. Can you please build and test an image including this PR and report back?

**Comment by kaiyu22** [comment] 2017-03-28 07:53
Sure, I will report later.

**Comment by kaiyu22** [comment] 2017-03-29 01:40
@jleveque : After checking, the image which includes PR#434 has fixed this reboot issue.

**Comment by stcheng** [comment] 2017-03-29 01:41
@kaiyu22 thanks. I will close this issue.

**Closed by stcheng** 2017-03-29 01:41 UTC
Labels: bug
