### ISSUE TITLE
[drop_counters] test_configurable_drop_counters.test_neighbor_link_down[PORT_INGRESS_DROPS-L3_EGRESS_LINK_DOWN] fails because drop counter not incremented

### ISSUE THREAD

**Issue by theasianpianist** [Azure/sonic-buildimage#8101] opened 2021-07-07 00:52 UTC
```
testbed_params = {'physical_port_map': {1: 'Ethernet4', 2: 'Ethernet8', 3: 'Ethernet12', 4: 'Ethernet16', ...}, 'vlan_interface': {'add....0.1', 'attachto': u'Vlan1000', 'mask': u'255.255.248.0', 'prefixlen': 21, ...}, 'vlan_ports': [1, 2, 3, 4, 5, 6, ...]}
setup_counters = <function _setup_counters at 0x7f1f85fccf50>
duthosts = <tests.common.devices.duthosts.DutHosts object at 0x7f1f8ec7cf50>
rand_one_dut_hostname = 'str2-7050cx3-acs-06'
mock_server = {'fanout_intf': 'Ethernet47/1', 'fanout_neighbor': { os: 'eos', hostname: 'str2-7260cx3-acs-fan-10', device_type: 'FanoutLeaf' }, 'server_dst_addr': '192.168.2.82', 'server_dst_intf': 'Ethernet56', ...}
send_dropped_traffic = <function _runner at 0x7f1f8518ddd0>
drop_reason = 'L3_EGRESS_LINK_DOWN'

    @pytest.mark.parametrize("drop_reason", ["L3_EGRESS_LINK_DOWN"])
    def test_neighbor_link_down(testbed_params, setup_counters, duthosts, rand_one_dut_hostname, mock_server,
                                send_dropped_traffic, drop_reason):
        """
        Verifies counters that check for a neighbor link being down.
    
        Note:
            This test works by mocking a server within a VLAN, thus the T0
            topology is required.
    
        Args:
            drop_reason (str): The drop reason being tested.
        """
        duthost = duthosts[rand_one_dut_hostname]
        counter_type = setup_counters([drop_reason])
    
        rx_port = random.choice([port
                                 for port in testbed_params["physical_port_map"].keys()
                                 if port != mock_server["server_dst_port"]])
        rx_mac = duthost.get_dut_iface_mac(testbed_params["physical_port_map"][rx_port])
        logging.info("Selected port %s, mac = %s to send traffic", rx_port, rx_mac)
    
        src_mac = "DE:AD:BE:EF:12:34"
        src_ip = MOCK_DEST_IP
        pkt = _get_simple_ip_packet(src_mac, rx_mac, src_ip, mock_server["server_dst_addr"])
    
        try:
            mock_server["fanout_neighbor"].shutdown(mock_server["fanout_intf"])
>           send_dropped_traffic(counter_type, pkt, rx_port)

counter_type = 'PORT_INGRESS_DROPS'
drop_reason = 'L3_EGRESS_LINK_DOWN'
duthost    = <MultiAsicSonicHost> str2-7050cx3-acs-06
duthosts   = <tests.common.devices.duthosts.DutHosts object at 0x7f1f8ec7cf50>
mock_server = {'fanout_intf': 'Ethernet47/1', 'fanout_neighbor': { os: 'eos', hostname: 'str2-7260cx3-acs-fan-10', device_type: 'FanoutLeaf' }, 'server_dst_addr': '192.168.2.82', 'server_dst_intf': 'Ethernet56', ...}
pkt        = <Ether  dst=d4:af:f7:4d:a4:44 src=DE:AD:BE:EF:12:34 type=0x800 |<IP  ihl=None ...16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>
port       = 34
rand_one_dut_hostname = 'str2-7050cx3-acs-06'
rx_mac     = u'd4:af:f7:4d:a4:44'
rx_port    = 28
send_dropped_traffic = <function _runner at 0x7f1f8518ddd0>
setup_counters = <function _setup_counters at 0x7f1f85fccf50>
src_ip     = '2.2.2.2'
src_mac    = 'DE:AD:BE:EF:12:34'
testbed_params = {'physical_port_map': {1: 'Ethernet4', 2: 'Ethernet8', 3: 'Ethernet12', 4: 'Ethernet16', ...}, 'vlan_interface': {'add....0.1', 'attachto': u'Vlan1000', 'mask': u'255.255.248.0', 'prefixlen': 21, ...}, 'vlan_ports': [1, 2, 3, 4, 5, 6, ...]}

drop_packets/test_configurable_drop_counters.py:68: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

counter_type = 'PORT_INGRESS_DROPS'
pkt = <Ether  dst=d4:af:f7:4d:a4:44 src=DE:AD:BE:EF:12:34 type=0x800 |<IP  ihl=None ...16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>
rx_port = 28

    def _runner(counter_type, pkt, rx_port):
        duthost.command("sonic-clear dropcounters")
    
        logging.info("Sending traffic from ptf on port %s", rx_port)
        _send_packets(duthost, ptfadapter, pkt, rx_port)
    
        def _check_drops():
            dst_port = testbed_params["physical_port_map"][rx_port]
            recv_count = cdc.get_drop_counts(duthost,
                                             counter_type,
                                             "TEST",
                                             dst_port)
            logging.info("Received %s drops on port %s, expected %s",
                         recv_count, dst_port, PACKET_COUNT)
            return recv_count == PACKET_COUNT
    
>       pytest_assert(wait_until(5, 1, _check_drops), "Expected {} drops".format(PACKET_COUNT))
E       Failed: Expected 1000 drops

_check_drops = <function _check_drops at 0x7f1f85f008d0>
counter_type = 'PORT_INGRESS_DROPS'
duthost    = <MultiAsicSonicHost> str2-7050cx3-acs-06
pkt        = <Ether  dst=d4:af:f7:4d:a4:44 src=DE:AD:BE:EF:12:34 type=0x800 |<IP  ihl=None ...16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f !"#$%&\'()*+,-./0123456789:;<=>?@A' |>>>
ptfadapter = <tests.common.plugins.ptfadapter.ptfadapter.PtfTestAdapter testMethod=runTest>
rx_port    = 28
testbed_params = {'physical_port_map': {1: 'Ethernet4', 2: 'Ethernet8', 3: 'Ethernet12', 4: 'Ethernet16', ...}, 'vlan_interface': {'add....0.1', 'attachto': u'Vlan1000', 'mask': u'255.255.248.0', 'prefixlen': 21, ...}, 'vlan_ports': [1, 2, 3, 4, 5, 6, ...]}

drop_packets/test_configurable_drop_counters.py:244: Failed
```

**Comment by theasianpianist** [comment] 2021-07-07 01:46
Possible related to https://github.com/Azure/sonic-buildimage/issues/8031

**Comment by theasianpianist** [comment] 2021-07-14 01:46
CS00012197146

**Comment by vaibhavhd** [comment] 2021-07-16 01:33
Duplicate of https://github.com/Azure/sonic-buildimage/issues/8031

**Comment by vaibhavhd** [comment] 2021-08-06 01:43
Closing as this is a duplicate.

**Closed by vaibhavhd** 2021-08-06 01:43 UTC
Labels: Issues for 202012, Dual ToR Platform :gemini:, flaky
