### ISSUE TITLE
[orchagent][warm-reboot] orchagent crashed after warm-reboot

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#5635] opened 2020-10-15 09:30 UTC
**Description**
orchagent crashed after warm-reboot even no test is running.
```
Oct 15 09:15:29.119161 str-dx010-acs-4 ERR swss#orchagent: :- wait: SELECT operation result: TIMEOUT on notify
Oct 15 09:15:29.119161 str-dx010-acs-4 ERR swss#orchagent: :- wait: failed to get response for notify
Oct 15 09:15:29.119891 str-dx010-acs-4 NOTICE swss#orchagent: :- set: setting attribute 0x10000001 status: SAI_STATUS_FAILURE
Oct 15 09:15:29.119891 str-dx010-acs-4 ERR swss#orchagent: :- initSaiRedis: Failed to notify syncd INIT_VIEW, rv:-1 gSwitchId 0
Oct 15 09:15:29.119891 str-dx010-acs-4 WARNING swss#orchagent: :- meta_sai_on_switch_shutdown_request: switch_id oid:0x0 is of type SAI_OBJECT_TYPE_NULL, but expected SAI_OBJECT_TYPE_SWITCH
Oct 15 09:15:29.120008 str-dx010-acs-4 ERR swss#orchagent: :- sai_serialize_object_meta_key: invalid object type value SAI_OBJECT_TYPE_NULL
Oct 15 09:15:29.120008 str-dx010-acs-4 NOTICE swss#orchagent: :- uninitialize: begin
Oct 15 09:15:29.121819 str-dx010-acs-4 INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::runtime_error'
Oct 15 09:15:29.121819 str-dx010-acs-4 INFO swss#supervisord: orchagent   what():  :- sai_serialize_object_meta_key: invalid object type value SAI_OBJECT_TYPE_NULL
Oct 15 09:15:29.175249 str-dx010-acs-4 DEBUG core_uploader.py: core_uploader.py: Received create event - /var/core/orchagent.1602753329.42.core.gz
```

**Steps to reproduce the issue:**
1. Perform a ```cold reboot``` and wait for DUT to be stable
```
admin@str-dx010-acs-4:~$ uptime
 09:13:00 up 11 min,  2 users,  load average: 0.62, 0.95, 0.74
```
2. Perform a ```warm-reboot```, and wait for DUT boot up
3. Orchagent crashed after DUT is boot up.

**Describe the results you received:**
warm-reboot restart DUT without any crash.

**Describe the results you expected:**
orchagent crashed unexpectedly after warm-reboot.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

```
 admin@str-dx010-acs-4:~$ show version

SONiC Software Version: SONiC.master.441-5e97574e
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: 5e97574e
Build date: Sun Oct 11 07:56:58 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100007
Uptime: 09:28:49 up 15 min,  1 user,  load average: 0.90, 1.00, 0.90

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-teamd                  latest                b64e23596b0c        394MB
docker-teamd                  master.441-5e97574e   b64e23596b0c        394MB
docker-sonic-mgmt-framework   latest                f4108fcdf83a        486MB
docker-sonic-mgmt-framework   master.441-5e97574e   f4108fcdf83a        486MB
docker-router-advertiser      latest                df77be56193a        359MB
docker-router-advertiser      master.441-5e97574e   df77be56193a        359MB
docker-platform-monitor       latest                caf88f414a2d        441MB
docker-platform-monitor       master.441-5e97574e   caf88f414a2d        441MB
docker-lldp                   latest                167c14768744        388MB
docker-lldp                   master.441-5e97574e   167c14768744        388MB
docker-dhcp-relay             latest                c3a85ba7865b        366MB
docker-dhcp-relay             master.441-5e97574e   c3a85ba7865b        366MB
docker-database               latest                bf20c891675f        359MB
docker-database               master.441-5e97574e   bf20c891675f        359MB
docker-orchagent              latest                8162b9a31fe8        407MB
docker-orchagent              master.441-5e97574e   8162b9a31fe8        407MB
docker-nat                    latest                23171afd199c        396MB
docker-nat                    master.441-5e97574e   23171afd199c        396MB
docker-sonic-telemetry        latest                48268a2c6b47        429MB
docker-sonic-telemetry        master.441-5e97574e   48268a2c6b47        429MB
docker-fpm-frr                latest                8c99da5360ac        410MB
docker-fpm-frr                master.441-5e97574e   8c99da5360ac        410MB
docker-sflow                  latest                8c7530901b5d        397MB
docker-sflow                  master.441-5e97574e   8c7530901b5d        397MB
docker-snmp                   latest                0ad3a19d96a7        399MB
docker-snmp                   master.441-5e97574e   0ad3a19d96a7        399MB
docker-syncd-brcm             latest                9ff9b866d0fe        542MB
docker-syncd-brcm             master.441-5e97574e   9ff9b866d0fe        542MB
   
```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```
[orchagent.1602753329.42.core.gz](https://github.com/Azure/sonic-buildimage/files/5383781/orchagent.1602753329.42.core.gz)
[syslog.zip](https://github.com/Azure/sonic-buildimage/files/5383799/syslog.zip)

**Comment by daall** [comment] 2020-10-21 04:55
Closing as duplicate of #5521.

**Closed by daall** 2020-10-21 04:55 UTC
Labels: Duplicate :dancing_women:, Master Branch Quality
