### ISSUE TITLE
FDB entry doesn't respect aging configuration

### ISSUE THREAD

**Issue by bingwang-ms** [Azure/sonic-buildimage#6002] opened 2020-11-23 12:03 UTC
**Description**
Test case ```test_crm_fdb_entry``` failed in latest image. I check ```sairedis``` log and noticed that it was because the fdb entries got aged only 10 seconds after the fdb config file was loaded.
```
2020-11-23.09:19:19.174655|c|SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x2600000000069b","mac":"00:00:00:00:00:52","switch_id":"oid:0x21000000000000"}|SAI_FDB_ENTRY_ATTR_TYPE=SAI_FDB_ENTRY_TYPE_DYNAMIC|SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID=oid:0x3a00000000069c|SAI_FDB_ENTRY_ATTR_PACKET_ACTION=SAI_PACKET_ACTION_FORWARD
2020-11-23.09:19:29.125012|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x2600000000069b\",\"mac\":\"00:00:00:00:00:52\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_AGED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a00000000069c"}]}]|
``` 
However, the configured timeout is 600 seconds.
```
root@str-dx010-acs-4:/var/log/swss# bcmcmd 'age'
age
Current age timer is 600.
drivshell>
```
[sairedis.rec.6.gz](https://github.com/Azure/sonic-buildimage/files/5582761/sairedis.rec.6.gz)

**Steps to reproduce the issue:**
The issue was observed in ```test_crm_fdb_entry```, but not easy to repro.
1. Run ```test_crm_fdb_entry```
2.
3.

**Describe the results you received:**
Test case ```test_crm_fdb_entry``` passes without error.

**Describe the results you expected:**
Test case ```test_crm_fdb_entry``` failed, and FDB entries got aged and were clear in 10 seconds.

**Additional information you deem important (e.g. issue happens only occasionally):**

    **Output of `show version`:**

 ```
 SONiC Software Version: SONiC.master.491-af654944
Distribution: Debian 10.6
Kernel: 4.19.0-9-2-amd64
Build commit: af654944
Build date: Sun Nov 15 11:20:25 UTC 2020
Built by: johnar@jenkins-worker-8

Platform: x86_64-cel_seastone-r0
HwSKU: Celestica-DX010-C32
ASIC: broadcom
Serial Number: DX010F2B118711MS100007
Uptime: 12:03:03 up 22 min,  2 users,  load average: 2.60, 2.97, 2.33

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-snmp                   latest                32e259e905f1        458MB
docker-snmp                   master.491-af654944   32e259e905f1        458MB
docker-teamd                  latest                7b81e6696fda        454MB
docker-teamd                  master.491-af654944   7b81e6696fda        454MB
docker-sonic-mgmt-framework   latest                5c1935209d08        578MB
docker-sonic-mgmt-framework   master.491-af654944   5c1935209d08        578MB
docker-router-advertiser      latest                35f218401a81        421MB
docker-router-advertiser      master.491-af654944   35f218401a81        421MB
docker-platform-monitor       latest                0c0fc1571140        534MB
docker-platform-monitor       master.491-af654944   0c0fc1571140        534MB
docker-lldp                   latest                4caf7e3adfbb        485MB
docker-lldp                   master.491-af654944   4caf7e3adfbb        485MB
docker-dhcp-relay             latest                bfa4574a3e32        428MB
docker-dhcp-relay             master.491-af654944   bfa4574a3e32        428MB
docker-database               latest                6f12088a213d        421MB
docker-database               master.491-af654944   6f12088a213d        421MB
docker-orchagent              latest                0afefebd7999        468MB
docker-orchagent              master.491-af654944   0afefebd7999        468MB
docker-nat                    latest                7a7557403aba        457MB
docker-nat                    master.491-af654944   7a7557403aba        457MB
docker-sonic-telemetry        latest                42b255c3f740        491MB
docker-sonic-telemetry        master.491-af654944   42b255c3f740        491MB
docker-fpm-frr                latest                80872db697c9        471MB
docker-fpm-frr                master.491-af654944   80872db697c9        471MB
docker-sflow                  latest                db4bcb44cb19        455MB
docker-sflow                  master.491-af654944   db4bcb44cb19        455MB
docker-syncd-brcm             latest                c4cd5010b4d2        536MB
docker-syncd-brcm             master.491-af654944   c4cd5010b4d2        536MB

 ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by prsunny** [comment] 2020-11-23 18:41
is this consistent? also, happening for all fdb entries?

**Comment by bingwang-ms** [comment] 2020-11-24 02:03
It's not consistent, but happening to all fdb entries. I suspect that if the aging timer is reset when we applying same FDB entries by swssconfig?

**Comment by anshuv-mfst** [comment] 2020-11-25 16:26
BRCM team to look into this issue (@ben-gale could you please help with assigning this issue)

**Comment by lguohan** [comment] 2020-12-02 02:44
looks like the age is set to 600 seconds.

```
admin@str-dx010-acs-4:~$ bcmcmd "age"
age
Current age timer is 600.
drivshell>
```

**Comment by bingwang-ms** [comment] 2020-12-02 08:19
I notices something interesting when repro this issue.
I inserted an MAC manually by loading a json with ```swssconfig```. There is only one entry in the json file.
```
[{"FDB_TABLE:Vlan1000:00-00-00-00-00-01": {"type": "dynamic", "port": "Ethernet4"}, "OP": "SET"}]
``` 
The ```sairedis``` log shows that the entry is cleared by a 600 seconds timer, and the timer is never reset when we load the json again.
```
2020-12-02.06:52:14.424066|c|SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000005e6","mac":"00:00:00:00:00:01","switch_id":"oid:0x21000000000000"}|SAI_FDB_ENTRY_ATTR_TYPE=SAI_FDB_ENTRY_TYPE_DYNAMIC|SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID=oid:0x3a0000000005f5|SAI_FDB_ENTRY_ATTR_PACKET_ACTION=SAI_PACKET_ACTION_FORWARD
2020-12-02.06:59:36.837488|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x260000000005e6\",\"mac\":\"00:00:00:00:00:01\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_AGED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a0000000005f5"}]}]|
2020-12-02.07:00:51.196500|c|SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000005e6","mac":"00:00:00:00:00:01","switch_id":"oid:0x21000000000000"}|SAI_FDB_ENTRY_ATTR_TYPE=SAI_FDB_ENTRY_TYPE_DYNAMIC|SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID=oid:0x3a0000000005f5|SAI_FDB_ENTRY_ATTR_PACKET_ACTION=SAI_PACKET_ACTION_FORWARD
2020-12-02.07:09:36.838766|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x260000000005e6\",\"mac\":\"00:00:00:00:00:01\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_AGED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a0000000005f5"}]}]|
2020-12-02.07:15:35.696633|c|SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000005e6","mac":"00:00:00:00:00:01","switch_id":"oid:0x21000000000000"}|SAI_FDB_ENTRY_ATTR_TYPE=SAI_FDB_ENTRY_TYPE_DYNAMIC|SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID=oid:0x3a0000000005f5|SAI_FDB_ENTRY_ATTR_PACKET_ACTION=SAI_PACKET_ACTION_FORWARD
2020-12-02.07:19:36.841947|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x260000000005e6\",\"mac\":\"00:00:00:00:00:01\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_AGED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a0000000005f5"}]}]|
2020-12-02.07:23:34.180952|c|SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000005e6","mac":"00:00:00:00:00:01","switch_id":"oid:0x21000000000000"}|SAI_FDB_ENTRY_ATTR_TYPE=SAI_FDB_ENTRY_TYPE_DYNAMIC|SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID=oid:0x3a0000000005f5|SAI_FDB_ENTRY_ATTR_PACKET_ACTION=SAI_PACKET_ACTION_FORWARD
2020-12-02.07:29:36.847702|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x260000000005e6\",\"mac\":\"00:00:00:00:00:01\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_AGED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a0000000005f5"}]}]|
2020-12-02.07:34:12.462530|c|SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x260000000005e6","mac":"00:00:00:00:00:01","switch_id":"oid:0x21000000000000"}|SAI_FDB_ENTRY_ATTR_TYPE=SAI_FDB_ENTRY_TYPE_DYNAMIC|SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID=oid:0x3a0000000005f5|SAI_FDB_ENTRY_ATTR_PACKET_ACTION=SAI_PACKET_ACTION_FORWARD
2020-12-02.07:39:36.845092|n|fdb_event|[{"fdb_entry":"{\"bvid\":\"oid:0x260000000005e6\",\"mac\":\"00:00:00:00:00:01\",\"switch_id\":\"oid:0x21000000000000\"}","fdb_event":"SAI_FDB_EVENT_AGED","list":[{"id":"SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID","value":"oid:0x3a0000000005f5"}]}]|
``` 
We can see that the FDB entry is cleared at ```06:59:36.837488```, ```07:09:36.838766```, ```07:19:36.841947```, ```07:29:36.847702``` and  ```07:39:36.845092``` no matter when we insert the FDB entry. So the manually added FDB may expire at any time.

**Comment by ben-gale** [comment] 2020-12-02 12:09
@anilkpandey - fyi .....

**Comment by bingwang-ms** [comment] 2020-12-10 03:31
Discussed with @prsunny offline, and I think it's an expected behavior. The FDB aging timer is running at a fixed cycle (10 minutes in this case) and any unavailable FDB entry is cleared. In other words, the FDB entry added at 9th minute might be cleared at 10th minute. 
To workaround the test issue in test_crm_fdb, I will update test code to set the FDB aging time to 0 in order to disable the FDB aging.

**Comment by prsunny** [comment] 2020-12-10 03:48
@ben-gale , @anilkpandey, can you confirm this?

**Comment by daall** [comment] 2020-12-23 02:57
This looks like expected behavior, closing.

**Closed by daall** 2020-12-23 02:57 UTC
Labels: Master Branch Quality
