### ISSUE TITLE
Vrf binding via cli is NOT working in 202012 version

### ISSUE THREAD

**Issue by TETA-Net** [Azure/sonic-buildimage#6803] opened 2021-02-17 08:14 UTC
In the master version and last version 202012, the cli command of vrf is not working correctly. I check if you edit `config_db.json` it works good . but command `sudo config interface vrf bind <ifname> <Vrf_name>` it can not set the setting.

I try it in vs build and  Broadcom Tomahawk serise. 
```
SONiC Software Version: SONiC.202012.7-c40e43aa
Distribution: Debian 10.7
Kernel: 4.19.0-9-2-amd64
Build commit: c40e43aa
Build date: Sat Jan 16 11:32:15 UTC 2021
Built by: johnar@jenkins-worker-12
```

**Comment by anshuv-mfst** [comment] 2021-02-17 16:11
Can you please more information: 
1. Show techsupport output
2. CLI output (to show error from CLI output)

**Comment by maksymbelei95** [comment] 2021-02-18 17:40
It might be the same problem as https://github.com/Azure/sonic-buildimage/issues/6209. I will make more detailed check and provide the result here.

**Comment by maksymbelei95** [comment] 2021-02-19 11:23
As I supposed, the issue is the same as #6209. With changes from https://github.com/Azure/sonic-utilities/pull/1325 works fine. Tested on:
```
SONiC Software Version: SONiC.202012.23-6361d36f
Distribution: Debian 10.8
Kernel: 4.19.0-12-2-amd64
Build commit: 6361d36f
Build date: Wed Feb 17 10:35:36 UTC 2021
Built by: johnar@jenkins-worker-2

Platform: x86_64-mlnx_msn2700-r0
HwSKU: Mellanox-SN2700
ASIC: mellanox
ASIC Count: 1
Serial Number: MT2028X35388
Uptime: 13:18:51 up 14 min,  1 user,  load average: 2.53, 3.23, 2.09

Docker images:
REPOSITORY                    TAG                  IMAGE ID            SIZE
docker-syncd-mlnx             202012.23-6361d36f   b5289fdc235e        543MB
docker-syncd-mlnx             latest               b5289fdc235e        543MB
docker-sflow                  202012.23-6361d36f   77f883481aba        410MB
docker-sflow                  latest               77f883481aba        410MB
docker-snmp                   202012.23-6361d36f   e3fad1ad756a        439MB
docker-snmp                   latest               e3fad1ad756a        439MB
docker-teamd                  202012.23-6361d36f   b23b0804bdb3        409MB
docker-teamd                  latest               b23b0804bdb3        409MB
docker-nat                    202012.23-6361d36f   d72fb4d3e362        412MB
docker-nat                    latest               d72fb4d3e362        412MB
docker-router-advertiser      202012.23-6361d36f   c0f7031ab009        397MB
docker-router-advertiser      latest               c0f7031ab009        397MB
docker-platform-monitor       202012.23-6361d36f   354d756dac5d        689MB
docker-platform-monitor       latest               354d756dac5d        689MB
docker-lldp                   202012.23-6361d36f   a7692f3a97cd        437MB
docker-lldp                   latest               a7692f3a97cd        437MB
docker-dhcp-relay             202012.23-6361d36f   02960f3c1786        404MB
docker-dhcp-relay             latest               02960f3c1786        404MB
docker-database               202012.23-6361d36f   348b46e6c995        397MB
docker-database               latest               348b46e6c995        397MB
docker-orchagent              202012.23-6361d36f   ac307558cd2f        426MB
docker-orchagent              latest               ac307558cd2f        426MB
docker-sonic-telemetry        202012.23-6361d36f   b3eafd190449        472MB
docker-sonic-telemetry        latest               b3eafd190449        472MB
docker-sonic-mgmt-framework   202012.23-6361d36f   a113e82e8264        615MB
docker-sonic-mgmt-framework   latest               a113e82e8264        615MB
docker-fpm-frr                202012.23-6361d36f   ee379c876821        426MB
docker-fpm-frr                latest               ee379c876821        426MB
```

https://github.com/Azure/sonic-utilities/pull/1325 could be cherry-picked into 202012. @liat-grozovik, could I ask you to label the PR to cherry-pick it to 202012?

**Comment by liat-grozovik** [comment] 2021-02-19 16:04
Will do

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TETA-Net** [comment] 2021-02-21 05:27
merged with #6209

**Comment by TETA-Net** [comment] 2021-02-23 13:14
> Can you please more information:
> 
>     1. Show techsupport output
> 
>     2. CLI output (to show error from CLI output)
```
admin@dhcppc8:~$ show techsupport 
/usr/local/bin/generate_dump: line 89: syntax error near unexpected token `fi'
/usr/local/bin/generate_dump: line 89: `    fi'
```

**Comment by liat-grozovik** [comment] 2021-02-23 14:17
@TETA-Net a new broken show techsupport is not the issue described in here.
the issue is functional and as mentioned below already merged to master. as if it is in 202012 depends now on the cherry pick process. this will be done as i added a label for it.

if you think there is a new issue for the techsupport generation please open a different bug and provide the full output of the command execution and the configuration you used at the time it was generated

**Closed** 2021-02-24 07:14 UTC
Labels: Awaiting Info :hourglass:
