### ISSUE TITLE
dpkg-query: error: failed to open package info file `/var/lib/dpkg/updates/0001' for reading: No such file or directory

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-buildimage#119] opened 2016-12-14 17:14 UTC
dh_perl -plibnl-3-200-udeb 
dh_shlibdeps -plibnl-3-200-udeb    
dpkg-query: error: failed to open package info file `/var/lib/dpkg/updates/0001' for reading: No such file or directory
dpkg-shlibdeps: error: dpkg-query --control-path libc6:amd64 shlibs gave error exit status 2
dh_shlibdeps: dpkg-shlibdeps -Tdebian/libnl-3-200-udeb.substvars -tudeb debian/libnl-3-200-udeb/lib/libnl-3.so.200.22.0 returned exit code 2
/usr/share/cdbs/1/rules/debhelper.mk:277: recipe for target 'binary-predeb-IMPL/libnl-3-200-udeb' failed
make[2]: *** [binary-predeb-IMPL/libnl-3-200-udeb] Error 2
make[2]: Leaving directory '/var/build/workspace/mellanox/buildimage-mlnx-all-pr/src/libnl3/libnl3'

**Comment by lguohan** [comment] 2017-03-07 01:31
https://sonic-jenkins.westus.cloudapp.azure.com/job/cavium/job/buildimage-cavm-all-pr/333/console

**Comment by yxieca** [comment] 2019-03-19 21:38
I wasn't able to repeat this issue. I have been always building with multiple jobs. Will take a look at the make file to see if there is anything obvious.

**Comment by TencentSwitchGroup** [comment] 2019-07-18 02:02
I got the same issue when building iproute2 from source.
What's the reason of this issue? Why `[build]: set build jobs to 1 by default #383` can fix it?

```
1119    dh_strip
1120    dh_makeshlibs
1121    debian/rules override_dh_shlibdeps
1122 make[3]: Entering directory '/sonic/src/iproute2/iproute2-4.9.0'
1123 dh_shlibdeps -a -Xq_atm.so -Xm_xt.so -Xm_ipt.so
1124 dpkg-query: error: failed to open package info file `/var/lib/dpkg/updates/0001' for reading: No such file or directory
1125 dpkg-shlibdeps: error: dpkg-query --control-path libelf1:amd64 symbols gave error exit status 2
1126 dh_shlibdeps: dpkg-shlibdeps -Tdebian/iproute2.substvars debian/iproute2/usr/bin/nstat debian/iproute2/usr/bin/lnstat debian/iproute2/usr/sbin/arpd debian/iproute2/usr/sbin/genl debian/iproute2/bin/ss debian/iproute2/bin/i     p debian/iproute2/sbin/tc debian/iproute2/sbin/rtacct debian/iproute2/sbin/bridge debian/iproute2/sbin/rtmon debian/iproute2/sbin/devlink debian/iproute2/sbin/tipc returned exit code 2
1127 debian/rules:23: recipe for target 'override_dh_shlibdeps' failed
1128 make[3]: *** [override_dh_shlibdeps] Error 2
1129 make[3]: Leaving directory '/sonic/src/iproute2/iproute2-4.9.0'
1130 debian/rules:15: recipe for target 'binary' failed
1131 make[2]: *** [binary] Error 2
1132 make[2]: Leaving directory '/sonic/src/iproute2/iproute2-4.9.0'
1133 dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
1134 Makefile:11: recipe for target '/sonic/target/debs/iproute2_4.9.0-1_amd64.deb' failed
1135 make[1]: *** [/sonic/target/debs/iproute2_4.9.0-1_amd64.deb] Error 2
1136 make[1]: Leaving directory '/sonic/src/iproute2'                            
```

**Comment by gpaussabrcm** [comment] 2019-07-29 14:48
We've also been seeing the same issue when building the broadcom and vs platforms. In our case, we're using:
SONIC_CONFIG_BUILD_JOBS = 8
SONIC_CONFIG_MAKE_JOBS = 8

The error is intermittent and occurs for different .deb packages, but is occurring more frequently as the overall build times have decreased. This seems to be a race condition within the dpkg tools, and while the name of the reported package info file varies (/var/lib/dpkg/update/0000, 0001, 0005, etc.), the subsequent dpkg-query error message for us is always the same (libc6:amd64 symbols):

`dpkg-shlibdeps: error: dpkg-query --control-path libc6:amd64 symbols gave error exit status 2`

At first, we thought this had something to do with the slave.mk dpkg_lock possibly not working in the SONIC_INSTALL_TARGETS rule, but the .deb packages where this is occurring are being built in the SONIC_MAKE_DEBS or SONIC_DPKG_DEBS rules where there is no external locking being used. Also, while we do share build servers among many developers and Jenkins jobs, we have seen this failure occur with a single SONiC build being run on a server, so the problem appears to be caused by building multiple .deb targets within a SONiC build (i.e. within a user's build container), rather than from multiple users building on the same server.

A web search turned up this Debian bug from 2016 [#848555](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848555) that seems like the same thing we're seeing. The status messages indicate it was combined ("merged") into an older existing bug [#423866](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=423866) that was discovered in 2007 in the dpkg utility, but has never been fixed in Debian (Severity: wishlist). Within the SONiC build container, the dpkg version is 1.18.25 (amd64).

Reverting to non-parallel builds is not an option for us, since we're trying to drive down SONiC build times to enable a workable CI process internally. Whereas this error used to occur once in a great while, it's now happening several times per day and has reached the point where it can no longer be waved off as just a fluke.

**Comment by yxieca** [comment] 2019-09-17 01:15
Looks like there are 2 proposed way to fix this issue: https://ubuntuforums.org/showthread.php?t=872210

**Comment by gpaussabrcm** [comment] 2019-09-17 12:36
> 
> 
> Looks like there are 2 proposed ways to fix this issue: https://ubuntuforums.org/showthread.php?t=872210

Looks like that's for a different issue related to /var/lib/dpkg/available, not /var/lib/dpkg/updates/nnnn. Also, the issue seen during a SONiC build occurs during the creation of any of the .deb files (i.e. executing debian/rules), therefore modifying the dpkg installation on a shared build host during the build is not the solution for this case.

We're still seeing this particular error too often for comfort and do not know of a way to fix it short of serializing the .deb builds, which is not an option for us. We've added some external tooling to automatically retry (one time) a SONiC build that fails, in hopes that if this dpkg error occurred, it won't occur the second time around. Far from ideal, but it helps make our CI process a little more resilient to these transient errors.

We've considered upgrading the dpkg version on our Ubuntu 16.04 build servers, but without a known fix identified by the dpkg maintainers, there's no guarantee this will help.

**Comment by jleveque** [comment] 2019-09-17 18:54
@gpaussabrcm: We have occasionally seen both `/var/lib/dpkg/available/nnnn` and `/var/lib/dpkg/updates/nnnn` error messages. We believe they may both be symptoms of the same issue.

**Comment by lguohan** [comment] 2021-01-23 00:29
still seeing https://dev.azure.com/sonicswitch/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/1790/logs/33

however, it seems admindir is not changed, not sure if it is dpkg-buildpackage specific.

**Comment by lguohan** [comment] 2021-01-26 10:15
https://dev.azure.com/sonicswitch/be1b070f-be15-4154-aade-b1d3bfb17054/_apis/build/builds/1964/logs/12

**Comment by lguohan** [comment] 2021-01-26 11:16
looks like dpkg-buildpackage is calling dpkg-shlibdeps, and the admindir is not proprogated.

**Closed** 2022-01-19 16:07 UTC
Labels: Bug :bug:, Build :hammer:, Triaged

**Comment by ixodie** [comment] 2022-04-29 00:36
Getting this when building vs:
slave.mk:217: platform/vc/rules.mk: No such file or directory

Any ideas?
